window.BANK_PHYSICS = [
  // ============================================================
  // EASY TIER (single-step recall / definition / one-line substitution)
  // ============================================================
  {
    id: "phys-g11-vec-001",
    subject: "Physics",
    grade: 11,
    unit: "Vectors",
    difficulty: "easy",
    type: "definition",
    question: "Which of the following is a vector quantity?",
    options: { A: "Mass", B: "Temperature", C: "Velocity", D: "Time" },
    correct: "C",
    explanation: "A vector has both magnitude and direction. Velocity specifies speed and direction, while mass, temperature and time are scalars (magnitude only).",
    source: "curated"
  },
  {
    id: "phys-g11-vec-002",
    subject: "Physics",
    grade: 11,
    unit: "Vectors",
    difficulty: "easy",
    type: "calculation",
    question: "Two forces of 3 N and 4 N act at right angles to each other on a point. What is the magnitude of their resultant?",
    options: { A: "1 N", B: "5 N", C: "7 N", D: "12 N" },
    correct: "B",
    explanation: "For perpendicular vectors, R = √(3² + 4²) = √(9 + 16) = √25 = 5 N.",
    source: "curated"
  },
  {
    id: "phys-g11-vec-003",
    subject: "Physics",
    grade: 11,
    unit: "Vectors",
    difficulty: "easy",
    type: "conceptual",
    question: "When two vectors point in exactly opposite directions, the magnitude of their resultant equals:",
    options: { A: "The sum of their magnitudes", B: "The difference of their magnitudes", C: "Zero always", D: "The product of their magnitudes" },
    correct: "B",
    explanation: "Anti-parallel vectors partly cancel, so the resultant magnitude is |A − B|, the difference of the two magnitudes.",
    source: "curated"
  },
  {
    id: "phys-g11-mech-001",
    subject: "Physics",
    grade: 11,
    unit: "Motion in One and Two Dimensions",
    difficulty: "easy",
    type: "calculation",
    question: "A car travels 100 m in 5 s at constant velocity. What is its speed?",
    options: { A: "0.05 m/s", B: "20 m/s", C: "500 m/s", D: "25 m/s" },
    correct: "B",
    explanation: "Speed = distance / time = 100 m ÷ 5 s = 20 m/s.",
    source: "curated"
  },
  {
    id: "phys-g11-mech-002",
    subject: "Physics",
    grade: 11,
    unit: "Motion in One and Two Dimensions",
    difficulty: "easy",
    type: "definition",
    question: "What is the SI unit of acceleration?",
    options: { A: "m/s", B: "m/s²", C: "m·s", D: "N" },
    correct: "B",
    explanation: "Acceleration is the rate of change of velocity (m/s) per second, giving units of m/s².",
    source: "curated"
  },
  {
    id: "phys-g11-mech-003",
    subject: "Physics",
    grade: 11,
    unit: "Motion in One and Two Dimensions",
    difficulty: "easy",
    type: "calculation",
    question: "An object starts from rest and accelerates uniformly at 2 m/s² for 4 s. What is its final velocity?",
    options: { A: "2 m/s", B: "6 m/s", C: "8 m/s", D: "0.5 m/s" },
    correct: "C",
    explanation: "Using v = u + at with u = 0: v = 0 + (2)(4) = 8 m/s.",
    source: "curated"
  },
  {
    id: "phys-g11-dyn-001",
    subject: "Physics",
    grade: 11,
    unit: "Dynamics / Newton's Laws",
    difficulty: "easy",
    type: "calculation",
    question: "A net force of 10 N acts on a 2 kg object. What is its acceleration?",
    options: { A: "20 m/s²", B: "0.2 m/s²", C: "5 m/s²", D: "12 m/s²" },
    correct: "C",
    explanation: "Newton's second law: a = F/m = 10 N ÷ 2 kg = 5 m/s².",
    source: "curated"
  },
  {
    id: "phys-g11-dyn-002",
    subject: "Physics",
    grade: 11,
    unit: "Dynamics / Newton's Laws",
    difficulty: "easy",
    type: "definition",
    question: "Newton's first law of motion is also known as the law of:",
    options: { A: "Acceleration", B: "Inertia", C: "Action–reaction", D: "Gravitation" },
    correct: "B",
    explanation: "Newton's first law states that an object stays at rest or in uniform motion unless acted on by a net force — this tendency to resist change is inertia.",
    source: "curated"
  },
  {
    id: "phys-g11-dyn-003",
    subject: "Physics",
    grade: 11,
    unit: "Dynamics / Newton's Laws",
    difficulty: "easy",
    type: "calculation",
    question: "What is the weight of a 10 kg object near Earth's surface? (g = 9.8 m/s²)",
    options: { A: "1.02 N", B: "10 N", C: "98 N", D: "9.8 N" },
    correct: "C",
    explanation: "Weight W = mg = (10 kg)(9.8 m/s²) = 98 N.",
    source: "curated"
  },
  {
    id: "phys-g11-rot-001",
    subject: "Physics",
    grade: 11,
    unit: "Rotational Motion and Torque",
    difficulty: "easy",
    type: "definition",
    question: "What is the SI unit of torque?",
    options: { A: "N/m", B: "N·m", C: "N·m²", D: "N·s" },
    correct: "B",
    explanation: "Torque = force × perpendicular distance, so its unit is newton·metre (N·m).",
    source: "curated"
  },
  {
    id: "phys-g11-rot-002",
    subject: "Physics",
    grade: 11,
    unit: "Rotational Motion and Torque",
    difficulty: "easy",
    type: "calculation",
    question: "A force of 20 N is applied perpendicularly at the end of a 0.5 m wrench. What is the torque about the pivot?",
    options: { A: "40 N·m", B: "10 N·m", C: "20.5 N·m", D: "0.025 N·m" },
    correct: "B",
    explanation: "Torque τ = F × r = (20 N)(0.5 m) = 10 N·m.",
    source: "curated"
  },
  {
    id: "phys-g11-grav-001",
    subject: "Physics",
    grade: 11,
    unit: "Gravitation / Orbital and Escape Velocity",
    difficulty: "easy",
    type: "conceptual",
    question: "According to Newton's law of gravitation, if the distance between two masses is doubled, the gravitational force becomes:",
    options: { A: "Half", B: "Double", C: "One quarter", D: "Four times" },
    correct: "C",
    explanation: "Gravitational force F ∝ 1/r². Doubling r gives a factor of 1/2² = 1/4, so the force becomes one quarter.",
    source: "curated"
  },
  {
    id: "phys-g11-elas-001",
    subject: "Physics",
    grade: 11,
    unit: "Elasticity and Static Equilibrium",
    difficulty: "easy",
    type: "calculation",
    question: "A spring of stiffness 200 N/m is stretched by 0.1 m. What is the restoring force? (Hooke's law)",
    options: { A: "2 N", B: "20 N", C: "2000 N", D: "0.5 N" },
    correct: "B",
    explanation: "Hooke's law: F = kx = (200 N/m)(0.1 m) = 20 N.",
    source: "curated"
  },
  {
    id: "phys-g11-heat-001",
    subject: "Physics",
    grade: 11,
    unit: "Heat and Calorimetry",
    difficulty: "easy",
    type: "definition",
    question: "What is the SI unit of heat energy?",
    options: { A: "Watt", B: "Newton", C: "Joule", D: "Pascal" },
    correct: "C",
    explanation: "Heat is a form of energy, and the SI unit of energy is the joule (J).",
    source: "curated"
  },
  {
    id: "phys-g11-heat-002",
    subject: "Physics",
    grade: 11,
    unit: "Heat and Calorimetry",
    difficulty: "easy",
    type: "calculation",
    question: "How much heat is needed to raise the temperature of 2 kg of water by 10 °C? (c = 4200 J/kg·°C)",
    options: { A: "8400 J", B: "84000 J", C: "420 J", D: "21000 J" },
    correct: "B",
    explanation: "Q = mcΔT = (2 kg)(4200 J/kg·°C)(10 °C) = 84000 J.",
    source: "curated"
  },
  {
    id: "phys-g12-estat-001",
    subject: "Physics",
    grade: 12,
    unit: "Electrostatics and Coulomb's Law",
    difficulty: "easy",
    type: "definition",
    question: "Like charges __________ and unlike charges __________.",
    options: { A: "attract; repel", B: "repel; attract", C: "attract; attract", D: "repel; repel" },
    correct: "B",
    explanation: "By Coulomb's law, charges of the same sign repel each other, while charges of opposite sign attract.",
    source: "curated"
  },
  {
    id: "phys-g12-estat-002",
    subject: "Physics",
    grade: 12,
    unit: "Electrostatics and Coulomb's Law",
    difficulty: "easy",
    type: "definition",
    question: "What is the SI unit of electric charge?",
    options: { A: "Volt", B: "Ampere", C: "Coulomb", D: "Farad" },
    correct: "C",
    explanation: "Electric charge is measured in coulombs (C); 1 C = 1 A·s.",
    source: "curated"
  },
  {
    id: "phys-g12-cap-001",
    subject: "Physics",
    grade: 12,
    unit: "Capacitors",
    difficulty: "easy",
    type: "definition",
    question: "What is the SI unit of capacitance?",
    options: { A: "Henry", B: "Farad", C: "Ohm", D: "Tesla" },
    correct: "B",
    explanation: "Capacitance is measured in farads (F), where 1 F = 1 coulomb per volt (C/V).",
    source: "curated"
  },
  {
    id: "phys-g12-curr-001",
    subject: "Physics",
    grade: 12,
    unit: "Current Electricity and Resistor Networks",
    difficulty: "easy",
    type: "calculation",
    question: "A 12 V battery drives a current through a 4 Ω resistor. What is the current? (Ohm's law)",
    options: { A: "48 A", B: "3 A", C: "0.33 A", D: "16 A" },
    correct: "B",
    explanation: "Ohm's law: I = V/R = 12 V ÷ 4 Ω = 3 A.",
    source: "curated"
  },
  {
    id: "phys-g12-curr-002",
    subject: "Physics",
    grade: 12,
    unit: "Current Electricity and Resistor Networks",
    difficulty: "easy",
    type: "calculation",
    question: "Two resistors of 3 Ω and 6 Ω are connected in series. What is the total resistance?",
    options: { A: "2 Ω", B: "9 Ω", C: "0.5 Ω", D: "18 Ω" },
    correct: "B",
    explanation: "Resistors in series add directly: R_total = 3 Ω + 6 Ω = 9 Ω.",
    source: "curated"
  },
  {
    id: "phys-g12-mag-001",
    subject: "Physics",
    grade: 12,
    unit: "Magnetism and Electromagnetism / Induction",
    difficulty: "easy",
    type: "definition",
    question: "What is the SI unit of magnetic flux density (magnetic field strength B)?",
    options: { A: "Weber", B: "Tesla", C: "Henry", D: "Gauss" },
    correct: "B",
    explanation: "Magnetic flux density B is measured in teslas (T); 1 T = 1 Wb/m².",
    source: "curated"
  },
  {
    id: "phys-g12-wave-001",
    subject: "Physics",
    grade: 12,
    unit: "Waves and Geometric Optics",
    difficulty: "easy",
    type: "calculation",
    question: "A wave has a frequency of 50 Hz and a wavelength of 4 m. What is its speed?",
    options: { A: "12.5 m/s", B: "54 m/s", C: "200 m/s", D: "0.08 m/s" },
    correct: "C",
    explanation: "Wave speed v = fλ = (50 Hz)(4 m) = 200 m/s.",
    source: "curated"
  },
  {
    id: "phys-g12-wave-002",
    subject: "Physics",
    grade: 12,
    unit: "Waves and Geometric Optics",
    difficulty: "easy",
    type: "conceptual",
    question: "Which type of mirror always produces an upright, diminished (virtual) image of distant objects?",
    options: { A: "Concave mirror", B: "Plane mirror", C: "Convex mirror", D: "Parabolic mirror" },
    correct: "C",
    explanation: "A convex (diverging) mirror always forms an upright, reduced, virtual image regardless of object distance, which is why it is used as a wide-view side mirror.",
    source: "curated"
  },
  {
    id: "phys-g12-nuc-001",
    subject: "Physics",
    grade: 12,
    unit: "Nuclear Physics",
    difficulty: "easy",
    type: "definition",
    question: "Which type of radiation has the greatest penetrating power?",
    options: { A: "Alpha", B: "Beta", C: "Gamma", D: "All equal" },
    correct: "C",
    explanation: "Gamma rays are high-energy photons with no charge and no mass, so they penetrate far more than the heavier alpha or lighter beta particles.",
    source: "curated"
  },
  {
    id: "phys-g12-elec-001",
    subject: "Physics",
    grade: 12,
    unit: "Electronics (Diodes, Transistors, Logic Gates)",
    difficulty: "easy",
    type: "definition",
    question: "An ideal diode allows current to flow:",
    options: { A: "In both directions equally", B: "Only in the forward (forward-biased) direction", C: "Only when reverse-biased", D: "Never" },
    correct: "B",
    explanation: "A diode conducts only when forward-biased; when reverse-biased it blocks current, so it acts as a one-way valve for current.",
    source: "curated"
  },
  {
    id: "phys-g12-elec-002",
    subject: "Physics",
    grade: 12,
    unit: "Electronics (Diodes, Transistors, Logic Gates)",
    difficulty: "easy",
    type: "conceptual",
    question: "A two-input AND gate outputs logic 1 only when:",
    options: { A: "At least one input is 1", B: "Both inputs are 1", C: "Both inputs are 0", D: "The inputs differ" },
    correct: "B",
    explanation: "An AND gate outputs 1 only if all inputs are 1; for two inputs that means A = 1 AND B = 1.",
    source: "curated"
  },

  // ============================================================
  // MEDIUM TIER (2-step reasoning or one standard formula)
  // ============================================================
  {
    id: "phys-g11-vec-101",
    subject: "Physics",
    grade: 11,
    unit: "Vectors",
    difficulty: "medium",
    type: "calculation",
    question: "A vector of magnitude 10 N makes a 30° angle with the horizontal. What is its horizontal (x) component? (cos 30° ≈ 0.866)",
    options: { A: "5 N", B: "8.66 N", C: "10 N", D: "0.866 N" },
    correct: "B",
    explanation: "The x-component is Fₓ = F cos θ = 10 × cos 30° = 10 × 0.866 = 8.66 N.",
    source: "curated"
  },
  {
    id: "phys-g11-vec-102",
    subject: "Physics",
    grade: 11,
    unit: "Vectors",
    difficulty: "medium",
    type: "calculation",
    question: "Two displacement vectors, 6 m east and 8 m north, are added. What is the magnitude of the resultant displacement?",
    options: { A: "14 m", B: "2 m", C: "10 m", D: "48 m" },
    correct: "C",
    explanation: "Perpendicular vectors: R = √(6² + 8²) = √(36 + 64) = √100 = 10 m.",
    source: "curated"
  },
  {
    id: "phys-g11-mech-101",
    subject: "Physics",
    grade: 11,
    unit: "Motion in One and Two Dimensions",
    difficulty: "medium",
    type: "calculation",
    question: "A ball is thrown vertically upward with an initial speed of 19.6 m/s. How high does it rise? (g = 9.8 m/s²)",
    options: { A: "9.8 m", B: "19.6 m", C: "39.2 m", D: "2 m" },
    correct: "B",
    explanation: "At the top v = 0. Using v² = u² − 2gh: 0 = (19.6)² − 2(9.8)h → h = 384.16 / 19.6 = 19.6 m.",
    source: "curated"
  },
  {
    id: "phys-g11-mech-102",
    subject: "Physics",
    grade: 11,
    unit: "Motion in One and Two Dimensions",
    difficulty: "medium",
    type: "calculation",
    question: "An object is dropped from rest. How far does it fall in 3 s? (g = 9.8 m/s²)",
    options: { A: "29.4 m", B: "44.1 m", C: "14.7 m", D: "88.2 m" },
    correct: "B",
    explanation: "s = ½gt² = ½(9.8)(3²) = ½(9.8)(9) = 44.1 m.",
    source: "curated"
  },
  {
    id: "phys-g11-mech-103",
    subject: "Physics",
    grade: 11,
    unit: "Motion in One and Two Dimensions",
    difficulty: "medium",
    type: "calculation",
    question: "A projectile is launched horizontally from a 20 m high cliff. How long is it in the air before hitting the ground? (g = 10 m/s², stated)",
    options: { A: "1 s", B: "2 s", C: "4 s", D: "0.5 s" },
    correct: "B",
    explanation: "Vertical fall: 20 = ½(10)t² → t² = 4 → t = 2 s. Horizontal launch speed does not affect fall time.",
    source: "curated"
  },
  {
    id: "phys-g11-mech-104",
    subject: "Physics",
    grade: 11,
    unit: "Motion in One and Two Dimensions",
    difficulty: "medium",
    type: "calculation",
    question: "A car decelerates uniformly from 30 m/s to 10 m/s over 5 s. What is its acceleration?",
    options: { A: "−4 m/s²", B: "−8 m/s²", C: "4 m/s²", D: "−2 m/s²" },
    correct: "A",
    explanation: "a = (v − u)/t = (10 − 30)/5 = −20/5 = −4 m/s² (the negative sign indicates deceleration).",
    source: "curated"
  },
  {
    id: "phys-g11-dyn-101",
    subject: "Physics",
    grade: 11,
    unit: "Dynamics / Newton's Laws",
    difficulty: "medium",
    type: "calculation",
    question: "A 5 kg block on a frictionless surface is pushed by a 15 N horizontal force. What is the magnitude of the acceleration?",
    options: { A: "75 m/s²", B: "3 m/s²", C: "0.33 m/s²", D: "10 m/s²" },
    correct: "B",
    explanation: "With no friction, a = F/m = 15 N ÷ 5 kg = 3 m/s².",
    source: "curated"
  },
  {
    id: "phys-g11-dyn-102",
    subject: "Physics",
    grade: 11,
    unit: "Dynamics / Newton's Laws",
    difficulty: "medium",
    type: "calculation",
    question: "A 2 kg block rests on a surface with coefficient of static friction 0.4. What minimum horizontal force is needed to start it moving? (g = 9.8 m/s²)",
    options: { A: "0.8 N", B: "7.84 N", C: "19.6 N", D: "4 N" },
    correct: "B",
    explanation: "Maximum static friction = μmg = (0.4)(2)(9.8) = 7.84 N, so a force just exceeding 7.84 N is required.",
    source: "curated"
  },
  {
    id: "phys-g11-dyn-103",
    subject: "Physics",
    grade: 11,
    unit: "Dynamics / Newton's Laws",
    difficulty: "medium",
    type: "calculation",
    question: "A 1000 kg car accelerates from 0 to 20 m/s in 10 s. What net force acts on it?",
    options: { A: "2000 N", B: "200 N", C: "20000 N", D: "500 N" },
    correct: "A",
    explanation: "a = 20/10 = 2 m/s²; F = ma = (1000)(2) = 2000 N.",
    source: "curated"
  },
  {
    id: "phys-g11-rot-101",
    subject: "Physics",
    grade: 11,
    unit: "Rotational Motion and Torque",
    difficulty: "medium",
    type: "calculation",
    question: "A force of 50 N is applied at 0.4 m from a pivot, at 30° to the lever arm. What is the torque? (sin 30° = 0.5)",
    options: { A: "20 N·m", B: "10 N·m", C: "17.3 N·m", D: "5 N·m" },
    correct: "B",
    explanation: "τ = rF sin θ = (0.4)(50)(sin 30°) = (0.4)(50)(0.5) = 10 N·m.",
    source: "curated"
  },
  {
    id: "phys-g11-rot-102",
    subject: "Physics",
    grade: 11,
    unit: "Rotational Motion and Torque",
    difficulty: "medium",
    type: "conceptual",
    question: "A solid disk and a hoop of the same mass and radius roll down an incline. Which reaches the bottom first?",
    options: { A: "The hoop", B: "The solid disk", C: "They arrive together", D: "Neither rolls" },
    correct: "B",
    explanation: "The solid disk has a smaller moment of inertia (½MR² vs MR² for the hoop), so more of its energy goes to translation, giving it greater linear acceleration and an earlier arrival.",
    source: "curated"
  },
  {
    id: "phys-g11-grav-101",
    subject: "Physics",
    grade: 11,
    unit: "Gravitation / Orbital and Escape Velocity",
    difficulty: "medium",
    type: "conceptual",
    question: "The escape velocity from a planet depends on which of the following?",
    options: { A: "The mass of the escaping object", B: "The planet's mass and radius", C: "The launch angle only", D: "The object's color" },
    correct: "B",
    explanation: "Escape velocity v = √(2GM/R) depends only on the planet's mass M and radius R, not on the escaping object's mass.",
    source: "curated"
  },
  {
    id: "phys-g11-grav-102",
    subject: "Physics",
    grade: 11,
    unit: "Gravitation / Orbital and Escape Velocity",
    difficulty: "medium",
    type: "calculation",
    question: "The acceleration due to gravity on a planet's surface is g = GM/R². If a planet has the same mass as Earth but twice the radius, its surface gravity is:",
    options: { A: "The same as Earth's", B: "Half of Earth's", C: "One quarter of Earth's", D: "Twice Earth's" },
    correct: "C",
    explanation: "g ∝ 1/R². Doubling R gives g multiplied by 1/2² = 1/4 of Earth's value.",
    source: "curated"
  },
  {
    id: "phys-g11-elas-101",
    subject: "Physics",
    grade: 11,
    unit: "Elasticity and Static Equilibrium",
    difficulty: "medium",
    type: "calculation",
    question: "A uniform 2 m beam carries a 60 N weight at one end. Where must a single support be placed so the beam balances, ignoring its own weight, with a 60 N weight also at the other end?",
    options: { A: "At the center (1 m)", B: "0.5 m from one end", C: "At one end", D: "It cannot balance" },
    correct: "A",
    explanation: "With equal weights at both ends, equal torques about the center are produced, so the support at the midpoint (1 m) gives balance.",
    source: "curated"
  },
  {
    id: "phys-g11-elas-102",
    subject: "Physics",
    grade: 11,
    unit: "Elasticity and Static Equilibrium",
    difficulty: "medium",
    type: "calculation",
    question: "A wire stretches 2 mm under a 100 N load. Assuming Hooke's law, how much will it stretch under 250 N?",
    options: { A: "2 mm", B: "5 mm", C: "1.25 mm", D: "0.8 mm" },
    correct: "B",
    explanation: "Extension is proportional to load: x₂ = x₁ × (F₂/F₁) = 2 mm × (250/100) = 5 mm.",
    source: "curated"
  },
  {
    id: "phys-g11-heat-101",
    subject: "Physics",
    grade: 11,
    unit: "Heat and Calorimetry",
    difficulty: "medium",
    type: "calculation",
    question: "A 0.5 kg metal block absorbs 9000 J and its temperature rises by 40 °C. What is its specific heat capacity?",
    options: { A: "450 J/kg·°C", B: "180000 J/kg·°C", C: "225 J/kg·°C", D: "720 J/kg·°C" },
    correct: "A",
    explanation: "c = Q/(mΔT) = 9000 / (0.5 × 40) = 9000 / 20 = 450 J/kg·°C.",
    source: "curated"
  },
  {
    id: "phys-g11-heat-102",
    subject: "Physics",
    grade: 11,
    unit: "Heat and Calorimetry",
    difficulty: "medium",
    type: "calculation",
    question: "Convert 27 °C to the Kelvin scale.",
    options: { A: "27 K", B: "246 K", C: "300 K", D: "327 K" },
    correct: "C",
    explanation: "T(K) = T(°C) + 273 = 27 + 273 = 300 K.",
    source: "curated"
  },
  {
    id: "phys-g12-estat-101",
    subject: "Physics",
    grade: 12,
    unit: "Electrostatics and Coulomb's Law",
    difficulty: "medium",
    type: "calculation",
    question: "Two point charges of +2 μC and +3 μC are 0.1 m apart. What is the magnitude of the force between them? (k = 9×10⁹ N·m²/C²)",
    options: { A: "5.4 N", B: "0.54 N", C: "54 N", D: "0.054 N" },
    correct: "A",
    explanation: "F = kq₁q₂/r² = (9×10⁹)(2×10⁻⁶)(3×10⁻⁶)/(0.1)² = (9×10⁹)(6×10⁻¹²)/0.01 = 0.054/0.01 = 5.4 N.",
    source: "curated"
  },
  {
    id: "phys-g12-estat-102",
    subject: "Physics",
    grade: 12,
    unit: "Electrostatics and Coulomb's Law",
    difficulty: "medium",
    type: "conceptual",
    question: "If the distance between two fixed charges is halved, the Coulomb force between them becomes:",
    options: { A: "Half", B: "Double", C: "Four times larger", D: "One quarter" },
    correct: "C",
    explanation: "F ∝ 1/r². Halving r multiplies the force by 1/(½)² = 4, so it becomes four times larger.",
    source: "curated"
  },
  {
    id: "phys-g12-cap-101",
    subject: "Physics",
    grade: 12,
    unit: "Capacitors",
    difficulty: "medium",
    type: "calculation",
    question: "A 4 μF capacitor is charged to 50 V. How much charge does it store? (Q = CV)",
    options: { A: "200 μC", B: "12.5 μC", C: "200 C", D: "0.08 μC" },
    correct: "A",
    explanation: "Q = CV = (4 μF)(50 V) = 200 μC.",
    source: "curated"
  },
  {
    id: "phys-g12-cap-102",
    subject: "Physics",
    grade: 12,
    unit: "Capacitors",
    difficulty: "medium",
    type: "calculation",
    question: "Two capacitors of 2 μF and 3 μF are connected in parallel. What is their combined capacitance?",
    options: { A: "1.2 μF", B: "5 μF", C: "0.83 μF", D: "6 μF" },
    correct: "B",
    explanation: "Capacitors in parallel add directly: C_total = 2 μF + 3 μF = 5 μF.",
    source: "curated"
  },
  {
    id: "phys-g12-curr-101",
    subject: "Physics",
    grade: 12,
    unit: "Current Electricity and Resistor Networks",
    difficulty: "medium",
    type: "calculation",
    question: "Two resistors of 4 Ω and 4 Ω are connected in parallel. What is the equivalent resistance?",
    options: { A: "8 Ω", B: "2 Ω", C: "4 Ω", D: "16 Ω" },
    correct: "B",
    explanation: "For two equal parallel resistors, R_eq = R/2 = 4/2 = 2 Ω (or 1/R_eq = 1/4 + 1/4 = 1/2).",
    source: "curated"
  },
  {
    id: "phys-g12-curr-102",
    subject: "Physics",
    grade: 12,
    unit: "Current Electricity and Resistor Networks",
    difficulty: "medium",
    type: "calculation",
    question: "A device draws 2 A from a 120 V supply. What is its power consumption?",
    options: { A: "60 W", B: "240 W", C: "122 W", D: "0.0167 W" },
    correct: "B",
    explanation: "Power P = VI = (120 V)(2 A) = 240 W.",
    source: "curated"
  },
  {
    id: "phys-g12-curr-103",
    subject: "Physics",
    grade: 12,
    unit: "Current Electricity and Resistor Networks",
    difficulty: "medium",
    type: "calculation",
    question: "A 10 Ω resistor carries a current of 3 A. How much power does it dissipate?",
    options: { A: "30 W", B: "90 W", C: "3.33 W", D: "13 W" },
    correct: "B",
    explanation: "Power dissipated P = I²R = (3)²(10) = 9 × 10 = 90 W.",
    source: "curated"
  },
  {
    id: "phys-g12-mag-101",
    subject: "Physics",
    grade: 12,
    unit: "Magnetism and Electromagnetism / Induction",
    difficulty: "medium",
    type: "calculation",
    question: "A wire of length 0.5 m carries 4 A perpendicular to a 0.2 T magnetic field. What is the force on the wire? (F = BIL)",
    options: { A: "0.4 N", B: "4 N", C: "0.04 N", D: "2.5 N" },
    correct: "A",
    explanation: "F = BIL = (0.2 T)(4 A)(0.5 m) = 0.4 N.",
    source: "curated"
  },
  {
    id: "phys-g12-mag-102",
    subject: "Physics",
    grade: 12,
    unit: "Magnetism and Electromagnetism / Induction",
    difficulty: "medium",
    type: "conceptual",
    question: "According to Lenz's law, an induced current always flows in a direction that:",
    options: { A: "Increases the change in flux that caused it", B: "Opposes the change in flux that caused it", C: "Is independent of the flux change", D: "Always flows clockwise" },
    correct: "B",
    explanation: "Lenz's law states the induced current opposes the change in magnetic flux producing it — a consequence of conservation of energy.",
    source: "curated"
  },
  {
    id: "phys-g12-acdc-101",
    subject: "Physics",
    grade: 12,
    unit: "AC vs DC Generators",
    difficulty: "medium",
    type: "conceptual",
    question: "The key structural difference between an AC generator and a DC generator is that the DC generator uses a:",
    options: { A: "Pair of slip rings", B: "Split-ring commutator", C: "Stronger magnet", D: "Larger coil only" },
    correct: "B",
    explanation: "A DC generator uses a split-ring commutator to reverse the output connections each half-cycle, producing one-directional (DC) output, whereas an AC generator uses slip rings.",
    source: "curated"
  },
  {
    id: "phys-g12-wave-101",
    subject: "Physics",
    grade: 12,
    unit: "Waves and Geometric Optics",
    difficulty: "medium",
    type: "calculation",
    question: "Light travels from air into glass with refractive index 1.5. If the angle of incidence is such that sin i = 0.6, what is sin r? (Snell's law)",
    options: { A: "0.9", B: "0.4", C: "0.6", D: "1.5" },
    correct: "B",
    explanation: "Snell's law: n₁ sin i = n₂ sin r → (1)(0.6) = (1.5) sin r → sin r = 0.6/1.5 = 0.4.",
    source: "curated"
  },
  {
    id: "phys-g12-wave-102",
    subject: "Physics",
    grade: 12,
    unit: "Waves and Geometric Optics",
    difficulty: "medium",
    type: "calculation",
    question: "An object is placed 30 cm from a converging lens of focal length 10 cm. Using 1/f = 1/v + 1/u, what is the image distance v?",
    options: { A: "7.5 cm", B: "15 cm", C: "20 cm", D: "40 cm" },
    correct: "B",
    explanation: "1/v = 1/f − 1/u = 1/10 − 1/30 = 3/30 − 1/30 = 2/30, so v = 30/2 = 15 cm.",
    source: "curated"
  },
  {
    id: "phys-g12-nuc-101",
    subject: "Physics",
    grade: 12,
    unit: "Nuclear Physics",
    difficulty: "medium",
    type: "calculation",
    question: "A radioactive isotope has a half-life of 8 days. What fraction of the original sample remains after 24 days?",
    options: { A: "1/2", B: "1/3", C: "1/8", D: "1/4" },
    correct: "C",
    explanation: "24 days = 3 half-lives, so the remaining fraction is (1/2)³ = 1/8.",
    source: "curated"
  },
  {
    id: "phys-g12-nuc-102",
    subject: "Physics",
    grade: 12,
    unit: "Nuclear Physics",
    difficulty: "medium",
    type: "conceptual",
    question: "When a nucleus emits an alpha particle, its mass number A and atomic number Z change by:",
    options: { A: "A decreases by 4, Z decreases by 2", B: "A unchanged, Z increases by 1", C: "A decreases by 2, Z decreases by 4", D: "A decreases by 4, Z increases by 2" },
    correct: "A",
    explanation: "An alpha particle is a helium nucleus (⁴₂He), so emitting it lowers the mass number by 4 and the atomic number by 2.",
    source: "curated"
  },
  {
    id: "phys-g12-elec-101",
    subject: "Physics",
    grade: 12,
    unit: "Electronics (Diodes, Transistors, Logic Gates)",
    difficulty: "medium",
    type: "conceptual",
    question: "A NOT gate (inverter) with input 1 produces an output of:",
    options: { A: "1", B: "0", C: "Both 0 and 1", D: "Undefined" },
    correct: "B",
    explanation: "A NOT gate inverts its input, so an input of 1 yields an output of 0.",
    source: "curated"
  },
  {
    id: "phys-g12-elec-102",
    subject: "Physics",
    grade: 12,
    unit: "Electronics (Diodes, Transistors, Logic Gates)",
    difficulty: "medium",
    type: "conceptual",
    question: "In a common circuit, a transistor is most commonly used as a:",
    options: { A: "Source of EMF", B: "Switch or amplifier", C: "Energy storage device", D: "Permanent magnet" },
    correct: "B",
    explanation: "A small base current controls a larger collector current, allowing a transistor to act as an electronic switch or amplifier.",
    source: "curated"
  },

  // ============================================================
  // HARD TIER (multi-step, combines two concepts, careful algebra)
  // ============================================================
  {
    id: "phys-g11-vec-201",
    subject: "Physics",
    grade: 11,
    unit: "Vectors",
    difficulty: "hard",
    type: "calculation",
    question: "Three forces act on a point: 5 N east, 5 N north, and 5√2 N to the southwest (i.e. at 225° from east). What is the magnitude of the resultant?",
    options: { A: "0 N", B: "5 N", C: "5√2 N", D: "10 N" },
    correct: "A",
    explanation: "East+north give a resultant of magnitude 5√2 N pointing northeast (45°). The third force is 5√2 N pointing southwest (225°), exactly opposite, so the total resultant is 0 N.",
    source: "curated"
  },
  {
    id: "phys-g11-vec-202",
    subject: "Physics",
    grade: 11,
    unit: "Vectors",
    difficulty: "hard",
    type: "calculation",
    question: "A boat heads straight across a river at 4 m/s while the current flows downstream at 3 m/s. The river is 80 m wide. How far downstream does the boat land?",
    options: { A: "60 m", B: "80 m", C: "106.7 m", D: "100 m" },
    correct: "A",
    explanation: "Crossing time = width / boat speed = 80/4 = 20 s. Downstream drift = current × time = 3 × 20 = 60 m.",
    source: "curated"
  },
  {
    id: "phys-g11-mech-201",
    subject: "Physics",
    grade: 11,
    unit: "Motion in One and Two Dimensions",
    difficulty: "hard",
    type: "calculation",
    question: "A projectile is launched at 20 m/s at 30° above the horizontal. What is its maximum height? (g = 10 m/s², sin 30° = 0.5)",
    options: { A: "5 m", B: "10 m", C: "20 m", D: "2.5 m" },
    correct: "A",
    explanation: "Vertical component u_y = 20 sin 30° = 10 m/s. Max height H = u_y²/(2g) = 100/(20) = 5 m.",
    source: "curated"
  },
  {
    id: "phys-g11-mech-202",
    subject: "Physics",
    grade: 11,
    unit: "Motion in One and Two Dimensions",
    difficulty: "hard",
    type: "calculation",
    question: "A projectile launched at 40 m/s at 30° above horizontal. What is its horizontal range? (g = 10 m/s², use R = u²sin2θ/g, sin 60° ≈ 0.866)",
    options: { A: "80 m", B: "138.6 m", C: "160 m", D: "69.3 m" },
    correct: "B",
    explanation: "R = u² sin(2θ)/g = (40²)(sin 60°)/10 = (1600)(0.866)/10 = 1385.6/10 = 138.6 m.",
    source: "curated"
  },
  {
    id: "phys-g11-mech-203",
    subject: "Physics",
    grade: 11,
    unit: "Motion in One and Two Dimensions",
    difficulty: "hard",
    type: "calculation",
    question: "A stone is thrown upward at 30 m/s. At what times is it at a height of 40 m? (g = 10 m/s²)",
    options: { A: "Only at 2 s", B: "At 2 s and 4 s", C: "At 1 s and 5 s", D: "At 3 s only" },
    correct: "B",
    explanation: "40 = 30t − 5t² → 5t² − 30t + 40 = 0 → t² − 6t + 8 = 0 → (t−2)(t−4)=0, so t = 2 s (going up) and t = 4 s (coming down).",
    source: "curated"
  },
  {
    id: "phys-g11-dyn-201",
    subject: "Physics",
    grade: 11,
    unit: "Dynamics / Newton's Laws",
    difficulty: "hard",
    type: "calculation",
    question: "Two blocks, 3 kg and 2 kg, are connected by a string over a frictionless pulley (Atwood machine). What is the acceleration of the system? (g = 10 m/s²)",
    options: { A: "2 m/s²", B: "10 m/s²", C: "1 m/s²", D: "5 m/s²" },
    correct: "A",
    explanation: "a = (m₁ − m₂)g/(m₁ + m₂) = (3 − 2)(10)/(3 + 2) = 10/5 = 2 m/s².",
    source: "curated"
  },
  {
    id: "phys-g11-dyn-202",
    subject: "Physics",
    grade: 11,
    unit: "Dynamics / Newton's Laws",
    difficulty: "hard",
    type: "calculation",
    question: "A 4 kg block slides down a frictionless incline of 30°. What is its acceleration? (g = 10 m/s², sin 30° = 0.5)",
    options: { A: "10 m/s²", B: "5 m/s²", C: "8.66 m/s²", D: "2.5 m/s²" },
    correct: "B",
    explanation: "On a frictionless incline a = g sin θ = 10 × sin 30° = 10 × 0.5 = 5 m/s² (mass cancels out).",
    source: "curated"
  },
  {
    id: "phys-g11-dyn-203",
    subject: "Physics",
    grade: 11,
    unit: "Dynamics / Newton's Laws",
    difficulty: "hard",
    type: "calculation",
    question: "A 1500 kg car moving at 20 m/s is brought to rest in 4 s. What average braking force was applied?",
    options: { A: "7500 N", B: "30000 N", C: "6000 N", D: "1875 N" },
    correct: "A",
    explanation: "a = (0 − 20)/4 = −5 m/s². F = ma = (1500)(−5) = −7500 N; the braking force magnitude is 7500 N.",
    source: "curated"
  },
  {
    id: "phys-g11-rot-201",
    subject: "Physics",
    grade: 11,
    unit: "Rotational Motion and Torque",
    difficulty: "hard",
    type: "calculation",
    question: "A uniform 4 m plank weighing 200 N rests on two supports, one at each end. A 600 N person stands 1 m from the left support. What force does the left support exert?",
    options: { A: "400 N", B: "550 N", C: "650 N", D: "500 N" },
    correct: "B",
    explanation: "Take torques about the right support: F_left(4) = 600(3) + 200(2) = 1800 + 400 = 2200, so F_left = 2200/4 = 550 N. (Check: F_right = 800 − 550 = 250 N.)",
    source: "curated"
  },
  {
    id: "phys-g11-rot-202",
    subject: "Physics",
    grade: 11,
    unit: "Rotational Motion and Torque",
    difficulty: "hard",
    type: "calculation",
    question: "A solid disk of moment of inertia 0.5 kg·m² experiences a net torque of 2 N·m. What is its angular acceleration?",
    options: { A: "1 rad/s²", B: "4 rad/s²", C: "0.25 rad/s²", D: "2.5 rad/s²" },
    correct: "B",
    explanation: "Rotational analogue of Newton's second law: α = τ/I = 2 N·m ÷ 0.5 kg·m² = 4 rad/s².",
    source: "curated"
  },
  {
    id: "phys-g11-grav-201",
    subject: "Physics",
    grade: 11,
    unit: "Gravitation / Orbital and Escape Velocity",
    difficulty: "hard",
    type: "calculation",
    question: "Earth's escape velocity is 11.2 km/s. A planet has the same density but twice Earth's radius. What is its escape velocity? (v_esc ∝ R√ρ for constant density)",
    options: { A: "5.6 km/s", B: "11.2 km/s", C: "22.4 km/s", D: "44.8 km/s" },
    correct: "C",
    explanation: "For constant density, M ∝ R³, so v_esc = √(2GM/R) ∝ √(R³/R) = R. Doubling R doubles v_esc to 22.4 km/s.",
    source: "curated"
  },
  {
    id: "phys-g11-grav-202",
    subject: "Physics",
    grade: 11,
    unit: "Gravitation / Orbital and Escape Velocity",
    difficulty: "hard",
    type: "calculation",
    question: "A satellite orbits Earth at radius r. If it moves to an orbit of radius 4r, by what factor does its orbital period change? (Kepler's third law: T² ∝ r³)",
    options: { A: "4", B: "8", C: "16", D: "64" },
    correct: "B",
    explanation: "T² ∝ r³, so T ∝ r^(3/2). Increasing r by 4 gives T multiplied by 4^(3/2) = (√4)³ = 2³ = 8.",
    source: "curated"
  },
  {
    id: "phys-g11-elas-201",
    subject: "Physics",
    grade: 11,
    unit: "Elasticity and Static Equilibrium",
    difficulty: "hard",
    type: "calculation",
    question: "A wire of length 2 m and cross-sectional area 1×10⁻⁶ m² stretches by 1 mm under a 100 N load. What is the Young's modulus? (Y = FL/(AΔL))",
    options: { A: "2×10¹¹ Pa", B: "2×10⁸ Pa", C: "5×10⁻¹² Pa", D: "1×10¹¹ Pa" },
    correct: "A",
    explanation: "Y = FL/(AΔL) = (100 × 2)/(1×10⁻⁶ × 1×10⁻³) = 200/(1×10⁻⁹) = 2×10¹¹ Pa.",
    source: "curated"
  },
  {
    id: "phys-g11-elas-202",
    subject: "Physics",
    grade: 11,
    unit: "Elasticity and Static Equilibrium",
    difficulty: "hard",
    type: "calculation",
    question: "A 100 N sign hangs from the midpoint of a horizontal wire fixed at both ends. Each half of the wire makes a 30° angle below the horizontal. What is the tension in each half? (sin 30° = 0.5)",
    options: { A: "50 N", B: "100 N", C: "200 N", D: "57.7 N" },
    correct: "B",
    explanation: "Vertical equilibrium: 2T sin 30° = 100 → 2T(0.5) = 100 → T = 100 N in each half of the wire.",
    source: "curated"
  },
  {
    id: "phys-g11-heat-201",
    subject: "Physics",
    grade: 11,
    unit: "Heat and Calorimetry",
    difficulty: "hard",
    type: "calculation",
    question: "How much heat is needed to melt 0.2 kg of ice at 0 °C into water at 0 °C? (latent heat of fusion L_f = 3.34×10⁵ J/kg)",
    options: { A: "6.68×10⁴ J", B: "1.67×10⁶ J", C: "3.34×10⁴ J", D: "6.68×10⁵ J" },
    correct: "A",
    explanation: "Q = mL_f = (0.2 kg)(3.34×10⁵ J/kg) = 6.68×10⁴ J (no temperature change occurs during melting).",
    source: "curated"
  },
  {
    id: "phys-g11-heat-202",
    subject: "Physics",
    grade: 11,
    unit: "Heat and Calorimetry",
    difficulty: "hard",
    type: "calculation",
    question: "0.5 kg of water at 80 °C is mixed with 0.5 kg of water at 20 °C. Assuming no heat loss, what is the final temperature?",
    options: { A: "40 °C", B: "50 °C", C: "60 °C", D: "100 °C" },
    correct: "B",
    explanation: "With equal masses of the same substance, the final temperature is the average: (80 + 20)/2 = 50 °C (heat lost by hot water equals heat gained by cold water).",
    source: "curated"
  },
  {
    id: "phys-g12-estat-201",
    subject: "Physics",
    grade: 12,
    unit: "Electrostatics and Coulomb's Law",
    difficulty: "hard",
    type: "calculation",
    question: "Two equal charges q are placed 2 m apart and repel with a force of 0.9 N. What is q? (k = 9×10⁹ N·m²/C²)",
    options: { A: "20 μC", B: "2 μC", C: "0.2 μC", D: "200 μC" },
    correct: "A",
    explanation: "F = kq²/r² → 0.9 = (9×10⁹)q²/(2²) → q² = 0.9×4/(9×10⁹) = 3.6/(9×10⁹) = 4×10⁻¹⁰ → q = 2×10⁻⁵ C = 20 μC.",
    source: "curated"
  },
  {
    id: "phys-g12-estat-202",
    subject: "Physics",
    grade: 12,
    unit: "Electrostatics and Coulomb's Law",
    difficulty: "hard",
    type: "calculation",
    question: "A point charge of 4 μC creates an electric field at a point 0.2 m away. What is the field magnitude? (E = kq/r², k = 9×10⁹ N·m²/C²)",
    options: { A: "9×10⁵ N/C", B: "1.8×10⁵ N/C", C: "3.6×10⁴ N/C", D: "9×10⁶ N/C" },
    correct: "A",
    explanation: "E = kq/r² = (9×10⁹)(4×10⁻⁶)/(0.2²) = (3.6×10⁴)/0.04 = 9×10⁵ N/C.",
    source: "curated"
  },
  {
    id: "phys-g12-cap-201",
    subject: "Physics",
    grade: 12,
    unit: "Capacitors",
    difficulty: "hard",
    type: "calculation",
    question: "Two capacitors, 6 μF and 3 μF, are connected in series. What is the equivalent capacitance?",
    options: { A: "9 μF", B: "2 μF", C: "4.5 μF", D: "0.5 μF" },
    correct: "B",
    explanation: "In series 1/C = 1/6 + 1/3 = 1/6 + 2/6 = 3/6 = 1/2, so C_eq = 2 μF.",
    source: "curated"
  },
  {
    id: "phys-g12-cap-202",
    subject: "Physics",
    grade: 12,
    unit: "Capacitors",
    difficulty: "hard",
    type: "calculation",
    question: "A 10 μF capacitor is charged to 200 V. How much energy is stored? (E = ½CV²)",
    options: { A: "0.2 J", B: "2 J", C: "0.1 J", D: "20 J" },
    correct: "A",
    explanation: "E = ½CV² = ½(10×10⁻⁶)(200²) = ½(10×10⁻⁶)(40000) = ½(0.4) = 0.2 J.",
    source: "curated"
  },
  {
    id: "phys-g12-curr-201",
    subject: "Physics",
    grade: 12,
    unit: "Current Electricity and Resistor Networks",
    difficulty: "hard",
    type: "calculation",
    question: "A 6 Ω resistor is in series with a parallel combination of two 4 Ω resistors. What is the total resistance of the network?",
    options: { A: "14 Ω", B: "8 Ω", C: "2 Ω", D: "10 Ω" },
    correct: "B",
    explanation: "The two 4 Ω in parallel give 2 Ω; in series with 6 Ω gives 6 + 2 = 8 Ω.",
    source: "curated"
  },
  {
    id: "phys-g12-curr-202",
    subject: "Physics",
    grade: 12,
    unit: "Current Electricity and Resistor Networks",
    difficulty: "hard",
    type: "calculation",
    question: "A 12 V battery is connected to a 2 Ω resistor in series with a 4 Ω resistor. What is the voltage across the 4 Ω resistor?",
    options: { A: "4 V", B: "8 V", C: "12 V", D: "6 V" },
    correct: "B",
    explanation: "Total R = 6 Ω, so I = 12/6 = 2 A. Voltage across the 4 Ω resistor = IR = (2)(4) = 8 V.",
    source: "curated"
  },
  {
    id: "phys-g12-curr-203",
    subject: "Physics",
    grade: 12,
    unit: "Current Electricity and Resistor Networks",
    difficulty: "hard",
    type: "calculation",
    question: "A battery of EMF 10 V and internal resistance 0.5 Ω is connected to a 4.5 Ω external resistor. What is the terminal voltage?",
    options: { A: "10 V", B: "9 V", C: "1 V", D: "8 V" },
    correct: "B",
    explanation: "I = EMF/(R + r) = 10/(4.5 + 0.5) = 10/5 = 2 A. Terminal voltage = IR = (2)(4.5) = 9 V.",
    source: "curated"
  },
  {
    id: "phys-g12-mag-201",
    subject: "Physics",
    grade: 12,
    unit: "Magnetism and Electromagnetism / Induction",
    difficulty: "hard",
    type: "calculation",
    question: "A coil of 200 turns experiences a uniform change of magnetic flux of 0.01 Wb in 0.5 s. What is the magnitude of the induced EMF? (Faraday's law)",
    options: { A: "4 V", B: "0.4 V", C: "40 V", D: "2 V" },
    correct: "A",
    explanation: "EMF = N(ΔΦ/Δt) = 200 × (0.01/0.5) = 200 × 0.02 = 4 V.",
    source: "curated"
  },
  {
    id: "phys-g12-mag-202",
    subject: "Physics",
    grade: 12,
    unit: "Magnetism and Electromagnetism / Induction",
    difficulty: "hard",
    type: "calculation",
    question: "A proton (charge 1.6×10⁻¹⁹ C) moves at 2×10⁶ m/s perpendicular to a 0.5 T field. What is the magnetic force on it? (F = qvB)",
    options: { A: "1.6×10⁻¹³ N", B: "1.6×10⁻¹⁹ N", C: "3.2×10⁻¹³ N", D: "8×10⁻¹⁴ N" },
    correct: "A",
    explanation: "F = qvB = (1.6×10⁻¹⁹)(2×10⁶)(0.5) = (1.6×10⁻¹⁹)(1×10⁶) = 1.6×10⁻¹³ N.",
    source: "curated"
  },
  {
    id: "phys-g12-acdc-201",
    subject: "Physics",
    grade: 12,
    unit: "AC vs DC Generators",
    difficulty: "hard",
    type: "calculation",
    question: "A generator coil of 100 turns and area 0.02 m² rotates at angular speed 50 rad/s in a 0.4 T field. What is the peak EMF? (EMF₀ = NBAω)",
    options: { A: "40 V", B: "4 V", C: "400 V", D: "0.4 V" },
    correct: "A",
    explanation: "Peak EMF = NBAω = (100)(0.4)(0.02)(50) = (100)(0.4)(1) = 40 V.",
    source: "curated"
  },
  {
    id: "phys-g12-wave-201",
    subject: "Physics",
    grade: 12,
    unit: "Waves and Geometric Optics",
    difficulty: "hard",
    type: "calculation",
    question: "A glass has refractive index 1.5. What is its critical angle for total internal reflection? (sin θc = 1/n, arcsin(0.667) ≈ 41.8°)",
    options: { A: "30°", B: "41.8°", C: "48.2°", D: "60°" },
    correct: "B",
    explanation: "sin θc = 1/n = 1/1.5 = 0.667, so θc = arcsin(0.667) ≈ 41.8°.",
    source: "curated"
  },
  {
    id: "phys-g12-wave-202",
    subject: "Physics",
    grade: 12,
    unit: "Waves and Geometric Optics",
    difficulty: "hard",
    type: "calculation",
    question: "An object 4 cm tall is placed 30 cm from a converging lens of focal length 10 cm. What is the height of the image? (image distance v = 15 cm)",
    options: { A: "8 cm", B: "2 cm", C: "4 cm", D: "1 cm" },
    correct: "B",
    explanation: "Magnification m = v/u = 15/30 = 0.5, so image height = 0.5 × 4 cm = 2 cm (inverted, real).",
    source: "curated"
  },
  {
    id: "phys-g12-nuc-201",
    subject: "Physics",
    grade: 12,
    unit: "Nuclear Physics",
    difficulty: "hard",
    type: "calculation",
    question: "A sample initially has 800 g of a radioactive isotope with half-life 5 years. How much remains after 15 years?",
    options: { A: "100 g", B: "200 g", C: "50 g", D: "400 g" },
    correct: "A",
    explanation: "15 years = 3 half-lives, so remaining = 800 × (1/2)³ = 800 × 1/8 = 100 g.",
    source: "curated"
  },
  {
    id: "phys-g12-nuc-202",
    subject: "Physics",
    grade: 12,
    unit: "Nuclear Physics",
    difficulty: "hard",
    type: "calculation",
    question: "Calculate the energy equivalent of a mass defect of 2×10⁻²⁸ kg. (c = 3×10⁸ m/s, E = mc²)",
    options: { A: "1.8×10⁻¹¹ J", B: "6×10⁻²⁰ J", C: "1.8×10⁻¹⁹ J", D: "9×10⁻¹² J" },
    correct: "A",
    explanation: "E = mc² = (2×10⁻²⁸)(3×10⁸)² = (2×10⁻²⁸)(9×10¹⁶) = 1.8×10⁻¹¹ J.",
    source: "curated"
  },
  {
    id: "phys-g12-elec-201",
    subject: "Physics",
    grade: 12,
    unit: "Electronics (Diodes, Transistors, Logic Gates)",
    difficulty: "hard",
    type: "conceptual",
    question: "A NAND gate has both inputs tied together to a single signal A. The combined gate behaves as which single gate?",
    options: { A: "AND gate", B: "OR gate", C: "NOT gate", D: "XOR gate" },
    correct: "C",
    explanation: "NAND(A, A) = NOT(A AND A) = NOT(A), so tying both NAND inputs together produces an inverter (NOT gate).",
    source: "curated"
  },
  {
    id: "phys-g12-elec-202",
    subject: "Physics",
    grade: 12,
    unit: "Electronics (Diodes, Transistors, Logic Gates)",
    difficulty: "hard",
    type: "conceptual",
    question: "A full-wave rectifier compared with a half-wave rectifier of the same AC input produces an output with:",
    options: { A: "Lower average DC and double ripple period", B: "Higher average DC and lower ripple", C: "No DC component", D: "Identical output" },
    correct: "B",
    explanation: "A full-wave rectifier inverts the negative half-cycles instead of discarding them, giving a higher average DC value and smaller, higher-frequency ripple than a half-wave rectifier.",
    source: "curated"
  },

  // ============================================================
  // IMPOSSIBLE TIER (olympiad-adjacent multi-concept synthesis)
  // ============================================================
  {
    id: "phys-g11-vec-301",
    subject: "Physics",
    grade: 11,
    unit: "Vectors",
    difficulty: "impossible",
    type: "calculation",
    question: "Two vectors of equal magnitude A have a resultant of magnitude A. What is the angle between them?",
    options: { A: "60°", B: "90°", C: "120°", D: "150°" },
    correct: "C",
    explanation: "R² = A² + A² + 2A²cos θ = A² → 2 + 2cos θ = 1 → cos θ = −1/2 → θ = 120°.",
    source: "curated"
  },
  {
    id: "phys-g11-vec-302",
    subject: "Physics",
    grade: 11,
    unit: "Vectors",
    difficulty: "impossible",
    type: "calculation",
    question: "A river flows at 3 m/s. A swimmer who swims at 5 m/s relative to the water wants to cross straight to the opposite bank. At what angle (from the straight-across direction, i.e. upstream) must she aim, and what is her crossing speed?",
    options: { A: "37° upstream, 4 m/s", B: "53° upstream, 4 m/s", C: "37° upstream, 3 m/s", D: "30° upstream, 4.33 m/s" },
    correct: "A",
    explanation: "To cancel the current she aims upstream so that 5 sin θ = 3 → sin θ = 0.6 → θ = 37°. Her across-bank speed = 5 cos 37° = 5(0.8) = 4 m/s.",
    source: "curated"
  },
  {
    id: "phys-g11-mech-301",
    subject: "Physics",
    grade: 11,
    unit: "Motion in One and Two Dimensions",
    difficulty: "impossible",
    type: "calculation",
    question: "A ball is projected at 25 m/s at 53° above horizontal from ground level. At what horizontal distance does it reach a height of 15 m on the way UP? (g = 10 m/s², sin 53° = 0.8, cos 53° = 0.6)",
    options: { A: "9 m", B: "12 m", C: "15 m", D: "6 m" },
    correct: "C",
    explanation: "u_y = 25(0.8) = 20 m/s; set 15 = 20t − 5t² → t² − 4t + 3 = 0 → t = 1 s (going up) or 3 s. At t = 1 s the horizontal distance x = u_x t = (25×0.6)(1) = 15 m.",
    source: "curated"
  },
  {
    id: "phys-g11-mech-302",
    subject: "Physics",
    grade: 11,
    unit: "Motion in One and Two Dimensions",
    difficulty: "impossible",
    type: "calculation",
    question: "Two balls are thrown vertically from the ground, the second 1 s after the first, each at 20 m/s. At what height above the ground do they meet? (g = 10 m/s²)",
    options: { A: "15 m", B: "18.75 m", C: "20 m", D: "11.25 m" },
    correct: "B",
    explanation: "Ball 1: y₁ = 20t − 5t². Ball 2 (launched 1 s later): y₂ = 20(t−1) − 5(t−1)². Set equal: 20t − 5t² = 20(t−1) − 5(t−1)² → 0 = −20 + 5(2t − 1) → 10t = 25 → t = 2.5 s. y₁ = 20(2.5) − 5(2.5²) = 50 − 31.25 = 18.75 m.",
    source: "curated"
  },
  {
    id: "phys-g11-dyn-301",
    subject: "Physics",
    grade: 11,
    unit: "Dynamics / Newton's Laws",
    difficulty: "impossible",
    type: "calculation",
    question: "A 2 kg block on a 30° incline is connected over a pulley to a hanging 3 kg block. The incline is frictionless. What is the acceleration of the system? (g = 10 m/s², sin 30° = 0.5)",
    options: { A: "4 m/s²", B: "2 m/s²", C: "5 m/s²", D: "6 m/s²" },
    correct: "A",
    explanation: "Driving force = hanging weight − component of incline weight = 3(10) − 2(10)(0.5) = 30 − 10 = 20 N. a = 20/(2+3) = 20/5 = 4 m/s².",
    source: "curated"
  },
  {
    id: "phys-g11-dyn-302",
    subject: "Physics",
    grade: 11,
    unit: "Dynamics / Newton's Laws",
    difficulty: "impossible",
    type: "calculation",
    question: "A 1 kg ball moving at 6 m/s collides head-on and elastically with a stationary 2 kg ball. What is the velocity of the 1 kg ball after the collision?",
    options: { A: "+2 m/s", B: "−2 m/s", C: "0 m/s", D: "+4 m/s" },
    correct: "B",
    explanation: "Elastic collision: v₁' = ((m₁−m₂)/(m₁+m₂))u₁ = ((1−2)/3)(6) = (−1/3)(6) = −2 m/s, so the lighter ball bounces back at 2 m/s.",
    source: "curated"
  },
  {
    id: "phys-g11-rot-301",
    subject: "Physics",
    grade: 11,
    unit: "Rotational Motion and Torque",
    difficulty: "impossible",
    type: "calculation",
    question: "A solid sphere (I = (2/5)mr²) rolls without slipping down an incline of angle 30°. What is its linear acceleration? (g = 10 m/s², sin 30° = 0.5)",
    options: { A: "5 m/s²", B: "3.57 m/s²", C: "2.5 m/s²", D: "10 m/s²" },
    correct: "B",
    explanation: "For a rolling body a = g sin θ /(1 + I/mr²) = 10(0.5)/(1 + 2/5) = 5/(7/5) = 5 × 5/7 = 25/7 ≈ 3.57 m/s².",
    source: "curated"
  },
  {
    id: "phys-g11-rot-302",
    subject: "Physics",
    grade: 11,
    unit: "Rotational Motion and Torque",
    difficulty: "impossible",
    type: "calculation",
    question: "A figure skater spinning at 2 rev/s pulls in her arms, reducing her moment of inertia to one third of its original value. What is her new angular speed? (conservation of angular momentum)",
    options: { A: "2 rev/s", B: "6 rev/s", C: "0.67 rev/s", D: "3 rev/s" },
    correct: "B",
    explanation: "Angular momentum is conserved: I₁ω₁ = I₂ω₂. With I₂ = I₁/3, ω₂ = ω₁(I₁/I₂) = 2 × 3 = 6 rev/s.",
    source: "curated"
  },
  {
    id: "phys-g11-grav-301",
    subject: "Physics",
    grade: 11,
    unit: "Gravitation / Orbital and Escape Velocity",
    difficulty: "impossible",
    type: "calculation",
    question: "A satellite is in a circular orbit just above a planet's surface where surface gravity is g and radius is R. Its orbital speed equals √(gR). For Earth (g = 9.8 m/s², R = 6.4×10⁶ m), this orbital speed is approximately:",
    options: { A: "7.9 km/s", B: "11.2 km/s", C: "3.1 km/s", D: "5.6 km/s" },
    correct: "A",
    explanation: "v = √(gR) = √(9.8 × 6.4×10⁶) = √(6.27×10⁷) ≈ 7920 m/s ≈ 7.9 km/s (the well-known low-Earth-orbit speed).",
    source: "curated"
  },
  {
    id: "phys-g11-grav-302",
    subject: "Physics",
    grade: 11,
    unit: "Gravitation / Orbital and Escape Velocity",
    difficulty: "impossible",
    type: "calculation",
    question: "Escape velocity is related to circular orbital velocity at the same radius by which factor? (v_esc / v_orbit)",
    options: { A: "2", B: "√2", C: "1/2", D: "4" },
    correct: "B",
    explanation: "v_orbit = √(GM/R) and v_esc = √(2GM/R), so v_esc/v_orbit = √2 (about 1.414).",
    source: "curated"
  },
  {
    id: "phys-g11-elas-301",
    subject: "Physics",
    grade: 11,
    unit: "Elasticity and Static Equilibrium",
    difficulty: "impossible",
    type: "calculation",
    question: "A uniform ladder of weight 200 N leans against a frictionless wall at 60° to the ground. The floor provides friction. What minimum coefficient of friction at the floor prevents slipping? (tan 60° ≈ 1.73)",
    options: { A: "0.29", B: "0.58", C: "0.87", D: "1.73" },
    correct: "A",
    explanation: "Taking torques and force balance for a ladder at angle θ to the floor, μ_min = 1/(2 tan θ) = 1/(2 × 1.73) = 1/3.46 ≈ 0.29.",
    source: "curated"
  },
  {
    id: "phys-g11-elas-302",
    subject: "Physics",
    grade: 11,
    unit: "Elasticity and Static Equilibrium",
    difficulty: "impossible",
    type: "calculation",
    question: "Two wires of the same material and length but radii r and 2r support the same load in turn. The ratio of their extensions (thin : thick) is:",
    options: { A: "1 : 1", B: "2 : 1", C: "4 : 1", D: "1 : 4" },
    correct: "C",
    explanation: "Extension ΔL = FL/(AY) ∝ 1/A ∝ 1/r². For radii r and 2r, areas are in ratio 1:4, so extensions are in ratio 4:1 (the thin wire stretches four times as much).",
    source: "curated"
  },
  {
    id: "phys-g11-heat-301",
    subject: "Physics",
    grade: 11,
    unit: "Heat and Calorimetry",
    difficulty: "impossible",
    type: "calculation",
    question: "A 0.1 kg block of ice at 0 °C is dropped into 0.5 kg of water at 40 °C in an insulated container. (L_f = 3.34×10⁵ J/kg, c_water = 4200 J/kg·°C). What is the final temperature, to the nearest degree?",
    options: { A: "0 °C with ice remaining", B: "About 20 °C", C: "About 28 °C", D: "About 34 °C" },
    correct: "B",
    explanation: "Heat to melt the ice = mL_f = 0.1×3.34×10⁵ = 3.34×10⁴ J. Energy balance: 0.5(4200)(40−T) = 3.34×10⁴ + 0.1(4200)T → 84000 − 2100T = 33400 + 420T → 50600 = 2520T → T ≈ 20 °C.",
    source: "curated"
  },
  {
    id: "phys-g11-heat-302",
    subject: "Physics",
    grade: 11,
    unit: "Heat and Calorimetry",
    difficulty: "impossible",
    type: "calculation",
    question: "An ideal monatomic gas doubles its absolute temperature at constant volume. By what factor does its pressure change? (Gay-Lussac's law: P/T = constant)",
    options: { A: "Halves", B: "Doubles", C: "Quadruples", D: "Unchanged" },
    correct: "B",
    explanation: "At constant volume P ∝ T (Gay-Lussac's law). Doubling the absolute temperature doubles the pressure.",
    source: "curated"
  },
  {
    id: "phys-g12-estat-301",
    subject: "Physics",
    grade: 12,
    unit: "Electrostatics and Coulomb's Law",
    difficulty: "impossible",
    type: "calculation",
    question: "Three equal charges +q sit at the corners of an equilateral triangle of side a. What is the magnitude of the net force on any one charge? (let F₀ = kq²/a²)",
    options: { A: "F₀", B: "2F₀", C: "√3 F₀", D: "3F₀" },
    correct: "C",
    explanation: "Each of the two other charges exerts F₀ at 60° to each other. Net = √(F₀² + F₀² + 2F₀²cos60°) = √(2F₀² + F₀²) = √3 F₀.",
    source: "curated"
  },
  {
    id: "phys-g12-estat-302",
    subject: "Physics",
    grade: 12,
    unit: "Electrostatics and Coulomb's Law",
    difficulty: "impossible",
    type: "calculation",
    question: "Charges +4q and +q are fixed at a distance d apart. At what point on the line between them is the electric field zero? (distance from the +q charge)",
    options: { A: "d/2", B: "d/3", C: "d/4", D: "2d/3" },
    correct: "B",
    explanation: "Set fields equal: k(4q)/x² = k(q)/(d−x)² where x is from +4q. → 4(d−x)² = x² → 2(d−x) = x → x = 2d/3 from +4q, which is d/3 from the +q charge.",
    source: "curated"
  },
  {
    id: "phys-g12-cap-301",
    subject: "Physics",
    grade: 12,
    unit: "Capacitors",
    difficulty: "impossible",
    type: "calculation",
    question: "A parallel-plate capacitor is charged by a battery, then disconnected, then a dielectric of constant k = 2 is inserted. What happens to the voltage across it?",
    options: { A: "Doubles", B: "Halves", C: "Unchanged", D: "Becomes zero" },
    correct: "B",
    explanation: "Disconnected means charge Q is fixed. Inserting the dielectric makes C' = kC = 2C, and V = Q/C', so V halves (V' = Q/2C = V/2).",
    source: "curated"
  },
  {
    id: "phys-g12-cap-302",
    subject: "Physics",
    grade: 12,
    unit: "Capacitors",
    difficulty: "impossible",
    type: "calculation",
    question: "A 3 μF and a 6 μF capacitor are connected in series across a 9 V battery. What is the charge on each capacitor?",
    options: { A: "18 μC", B: "27 μC", C: "9 μC", D: "54 μC" },
    correct: "A",
    explanation: "Series equivalent C = (3×6)/(3+6) = 18/9 = 2 μF. Charge Q = CV = (2 μF)(9 V) = 18 μC, and series capacitors carry equal charge, so each holds 18 μC.",
    source: "curated"
  },
  {
    id: "phys-g12-curr-301",
    subject: "Physics",
    grade: 12,
    unit: "Current Electricity and Resistor Networks",
    difficulty: "impossible",
    type: "calculation",
    question: "In a balanced Wheatstone bridge, three arms are 2 Ω, 4 Ω, and 6 Ω. If the 2 Ω and 4 Ω form one pair (P and Q) and 6 Ω is R, what is the fourth resistance S for balance? (P/Q = R/S)",
    options: { A: "3 Ω", B: "12 Ω", C: "8 Ω", D: "6 Ω" },
    correct: "B",
    explanation: "Balance condition P/Q = R/S → 2/4 = 6/S → S = 6 × 4/2 = 12 Ω.",
    source: "curated"
  },
  {
    id: "phys-g12-curr-302",
    subject: "Physics",
    grade: 12,
    unit: "Current Electricity and Resistor Networks",
    difficulty: "impossible",
    type: "calculation",
    question: "Twelve identical 1 Ω resistors form the edges of a cube. What is the equivalent resistance between two opposite (diagonal) corners of the cube?",
    options: { A: "1 Ω", B: "5/6 Ω", C: "3/4 Ω", D: "7/12 Ω" },
    correct: "B",
    explanation: "By symmetry the current splits 3-3-3 then 6 then 3-3-3, giving R = (1/3 + 1/6 + 1/3)R = (5/6)(1) = 5/6 Ω between opposite corners.",
    source: "curated"
  },
  {
    id: "phys-g12-mag-301",
    subject: "Physics",
    grade: 12,
    unit: "Magnetism and Electromagnetism / Induction",
    difficulty: "impossible",
    type: "calculation",
    question: "A conducting rod of length 0.5 m moves at 4 m/s perpendicular to a 0.3 T magnetic field. What EMF is induced across its ends? (EMF = BLv)",
    options: { A: "0.6 V", B: "6 V", C: "0.06 V", D: "1.2 V" },
    correct: "A",
    explanation: "Motional EMF = BLv = (0.3 T)(0.5 m)(4 m/s) = 0.6 V.",
    source: "curated"
  },
  {
    id: "phys-g12-mag-302",
    subject: "Physics",
    grade: 12,
    unit: "Magnetism and Electromagnetism / Induction",
    difficulty: "impossible",
    type: "calculation",
    question: "An ideal transformer steps 240 V down to 12 V. If the secondary delivers 5 A to a load, what is the current drawn from the primary? (P_in = P_out for ideal)",
    options: { A: "0.25 A", B: "5 A", C: "100 A", D: "1 A" },
    correct: "A",
    explanation: "For an ideal transformer V_p I_p = V_s I_s → I_p = (12 × 5)/240 = 60/240 = 0.25 A.",
    source: "curated"
  },
  {
    id: "phys-g12-acdc-301",
    subject: "Physics",
    grade: 12,
    unit: "AC vs DC Generators",
    difficulty: "impossible",
    type: "calculation",
    question: "An AC supply has a peak voltage of 311 V. What is its RMS voltage? (V_rms = V_peak/√2)",
    options: { A: "440 V", B: "220 V", C: "311 V", D: "155 V" },
    correct: "B",
    explanation: "V_rms = V_peak/√2 = 311/1.414 ≈ 220 V (the standard mains RMS value).",
    source: "curated"
  },
  {
    id: "phys-g12-wave-301",
    subject: "Physics",
    grade: 12,
    unit: "Waves and Geometric Optics",
    difficulty: "impossible",
    type: "calculation",
    question: "In Young's double-slit experiment, slits 0.5 mm apart are 2 m from the screen, lit by 500 nm light. What is the fringe spacing? (Δy = λD/d)",
    options: { A: "2 mm", B: "0.5 mm", C: "1 mm", D: "4 mm" },
    correct: "A",
    explanation: "Δy = λD/d = (500×10⁻⁹ × 2)/(0.5×10⁻³) = (1×10⁻⁶)/(0.5×10⁻³) = 2×10⁻³ m = 2 mm.",
    source: "curated"
  },
  {
    id: "phys-g12-wave-302",
    subject: "Physics",
    grade: 12,
    unit: "Waves and Geometric Optics",
    difficulty: "impossible",
    type: "calculation",
    question: "An object is placed at the focal point (u = f) of a converging lens. Where is the image formed?",
    options: { A: "At 2f", B: "At the focal point on the other side", C: "At infinity", D: "At the lens" },
    correct: "C",
    explanation: "Using 1/v = 1/f − 1/u with u = f: 1/v = 1/f − 1/f = 0, so v = infinity — the emerging rays are parallel and the image is at infinity.",
    source: "curated"
  },
  {
    id: "phys-g12-nuc-301",
    subject: "Physics",
    grade: 12,
    unit: "Nuclear Physics",
    difficulty: "impossible",
    type: "calculation",
    question: "A radioactive source has an activity that falls to 12.5% of its initial value after 30 hours. What is its half-life?",
    options: { A: "5 hours", B: "10 hours", C: "15 hours", D: "7.5 hours" },
    correct: "B",
    explanation: "12.5% = 1/8 = (1/2)³, so 3 half-lives occurred in 30 hours, giving a half-life of 30/3 = 10 hours.",
    source: "curated"
  },
  {
    id: "phys-g12-nuc-302",
    subject: "Physics",
    grade: 12,
    unit: "Nuclear Physics",
    difficulty: "impossible",
    type: "conceptual",
    question: "In the decay ²³⁸₉₂U → ²³⁴₉₀Th + X, what is particle X?",
    options: { A: "A beta particle", B: "A gamma photon", C: "An alpha particle", D: "A neutron" },
    correct: "C",
    explanation: "Mass number drops by 4 (238→234) and atomic number drops by 2 (92→90), which matches emission of an alpha particle (⁴₂He).",
    source: "curated"
  },
  {
    id: "phys-g12-elec-301",
    subject: "Physics",
    grade: 12,
    unit: "Electronics (Diodes, Transistors, Logic Gates)",
    difficulty: "impossible",
    type: "conceptual",
    question: "Two NOR gates: the output of the first (inputs A and B) feeds both inputs of the second. What single logic function does the overall circuit perform?",
    options: { A: "A AND B", B: "A OR B", C: "A NAND B", D: "NOT A" },
    correct: "B",
    explanation: "First gate gives NOR(A,B) = NOT(A OR B). Feeding that into a NOR used as an inverter gives NOT(NOT(A OR B)) = A OR B.",
    source: "curated"
  },
  {
    id: "phys-g12-elec-302",
    subject: "Physics",
    grade: 12,
    unit: "Electronics (Diodes, Transistors, Logic Gates)",
    difficulty: "impossible",
    type: "calculation",
    question: "A silicon diode (forward drop 0.7 V) is in series with a 230 Ω resistor across a 5 V DC supply. What is the current through the diode?",
    options: { A: "21.7 mA", B: "18.7 mA", C: "25 mA", D: "2.17 mA" },
    correct: "B",
    explanation: "Voltage across the resistor = 5 − 0.7 = 4.3 V. I = V/R = 4.3/230 ≈ 0.0187 A = 18.7 mA.",
    source: "curated"
  }
];
