window.BANK_BIOLOGY = [
  // ===================== EASY (recall / definition) =====================
  {
    id: "bio-g11-cell-001",
    subject: "Biology",
    grade: 11,
    unit: "Cell biology",
    difficulty: "easy",
    type: "definition",
    question: "Which organelle is described as the 'powerhouse of the cell'?",
    options: { A: "Nucleus", B: "Ribosome", C: "Mitochondrion", D: "Golgi apparatus" },
    correct: "C",
    explanation: "The mitochondrion is called the powerhouse because aerobic respiration there produces most of the cell's ATP.",
    source: "curated"
  },
  {
    id: "bio-g11-cell-002",
    subject: "Biology",
    grade: 11,
    unit: "Cell biology",
    difficulty: "easy",
    type: "conceptual",
    question: "Which structure is present in plant cells but absent in animal cells?",
    options: { A: "Cell membrane", B: "Cell wall", C: "Nucleus", D: "Mitochondrion" },
    correct: "B",
    explanation: "Plant cells have a rigid cellulose cell wall outside the membrane; animal cells have only a cell membrane.",
    source: "curated"
  },
  {
    id: "bio-g11-cell-003",
    subject: "Biology",
    grade: 11,
    unit: "Cell biology",
    difficulty: "easy",
    type: "definition",
    question: "The site of protein synthesis in a cell is the:",
    options: { A: "Lysosome", B: "Ribosome", C: "Vacuole", D: "Centriole" },
    correct: "B",
    explanation: "Ribosomes read mRNA and link amino acids into polypeptides, making them the site of protein synthesis.",
    source: "curated"
  },
  {
    id: "bio-g11-cell-004",
    subject: "Biology",
    grade: 11,
    unit: "Cell biology",
    difficulty: "easy",
    type: "conceptual",
    question: "Which of the following is a prokaryotic organism?",
    options: { A: "Bacterium", B: "Amoeba", C: "Yeast", D: "Human liver cell" },
    correct: "A",
    explanation: "Bacteria lack a membrane-bound nucleus and organelles, which defines a prokaryote; the others are eukaryotes.",
    source: "curated"
  },
  {
    id: "bio-g11-cell-005",
    subject: "Biology",
    grade: 11,
    unit: "Cell biology",
    difficulty: "easy",
    type: "definition",
    question: "Which organelle controls the activities of the cell and contains the genetic material?",
    options: { A: "Chloroplast", B: "Nucleus", C: "Endoplasmic reticulum", D: "Cytoplasm" },
    correct: "B",
    explanation: "The nucleus houses the DNA and directs cell activities through gene expression.",
    source: "curated"
  },
  {
    id: "bio-g11-bioc-001",
    subject: "Biology",
    grade: 11,
    unit: "Biochemistry/enzymes",
    difficulty: "easy",
    type: "definition",
    question: "Enzymes are biological catalysts made mainly of:",
    options: { A: "Lipids", B: "Proteins", C: "Carbohydrates", D: "Nucleic acids" },
    correct: "B",
    explanation: "Almost all enzymes are proteins whose folded shape creates an active site that speeds reactions.",
    source: "curated"
  },
  {
    id: "bio-g11-bioc-002",
    subject: "Biology",
    grade: 11,
    unit: "Biochemistry/enzymes",
    difficulty: "easy",
    type: "definition",
    question: "The specific region of an enzyme where the substrate binds is called the:",
    options: { A: "Active site", B: "Binding pocket of DNA", C: "Receptor site", D: "Reaction centre" },
    correct: "A",
    explanation: "The active site is the precisely shaped region that binds the substrate to catalyse the reaction.",
    source: "curated"
  },
  {
    id: "bio-g11-bioc-003",
    subject: "Biology",
    grade: 11,
    unit: "Biochemistry/enzymes",
    difficulty: "easy",
    type: "conceptual",
    question: "Which monomers make up proteins?",
    options: { A: "Glucose molecules", B: "Amino acids", C: "Nucleotides", D: "Fatty acids" },
    correct: "B",
    explanation: "Proteins are polymers of amino acids joined by peptide bonds.",
    source: "curated"
  },
  {
    id: "bio-g11-bioc-004",
    subject: "Biology",
    grade: 11,
    unit: "Biochemistry/enzymes",
    difficulty: "easy",
    type: "conceptual",
    question: "The basic structural unit (monomer) of carbohydrates such as starch is:",
    options: { A: "Amino acid", B: "Glycerol", C: "Monosaccharide", D: "Nucleotide" },
    correct: "C",
    explanation: "Starch is a polysaccharide built from many monosaccharide (glucose) units.",
    source: "curated"
  },
  {
    id: "bio-g12-gen-001",
    subject: "Biology",
    grade: 12,
    unit: "Genetics (Mendelian crosses, DNA/inheritance)",
    difficulty: "easy",
    type: "definition",
    question: "An organism with two identical alleles for a trait (e.g. TT or tt) is said to be:",
    options: { A: "Heterozygous", B: "Homozygous", C: "Hemizygous", D: "Recessive" },
    correct: "B",
    explanation: "Homozygous means both alleles for the gene are the same; heterozygous means they differ.",
    source: "curated"
  },
  {
    id: "bio-g12-gen-002",
    subject: "Biology",
    grade: 12,
    unit: "Genetics (Mendelian crosses, DNA/inheritance)",
    difficulty: "easy",
    type: "definition",
    question: "In DNA, adenine (A) always pairs with:",
    options: { A: "Guanine", B: "Cytosine", C: "Thymine", D: "Uracil" },
    correct: "C",
    explanation: "By complementary base pairing in DNA, adenine pairs with thymine (A–T) via two hydrogen bonds.",
    source: "curated"
  },
  {
    id: "bio-g12-gen-003",
    subject: "Biology",
    grade: 12,
    unit: "Genetics (Mendelian crosses, DNA/inheritance)",
    difficulty: "easy",
    type: "definition",
    question: "The observable physical characteristics of an organism are called its:",
    options: { A: "Genotype", B: "Phenotype", C: "Karyotype", D: "Allele" },
    correct: "B",
    explanation: "Phenotype is the expressed trait; genotype is the underlying allele combination.",
    source: "curated"
  },
  {
    id: "bio-g12-gen-004",
    subject: "Biology",
    grade: 12,
    unit: "Genetics (Mendelian crosses, DNA/inheritance)",
    difficulty: "easy",
    type: "definition",
    question: "DNA replication is described as semi-conservative because each new molecule contains:",
    options: { A: "Two new strands", B: "One old and one new strand", C: "Two old strands", D: "Only RNA strands" },
    correct: "B",
    explanation: "Each daughter DNA keeps one parental (template) strand and one newly made strand, hence semi-conservative.",
    source: "curated"
  },
  {
    id: "bio-g12-evo-001",
    subject: "Biology",
    grade: 12,
    unit: "Evolution",
    difficulty: "easy",
    type: "definition",
    question: "Who proposed the theory of evolution by natural selection?",
    options: { A: "Gregor Mendel", B: "Charles Darwin", C: "Louis Pasteur", D: "Robert Hooke" },
    correct: "B",
    explanation: "Charles Darwin proposed natural selection as the mechanism of evolution in 'On the Origin of Species'.",
    source: "curated"
  },
  {
    id: "bio-g12-evo-002",
    subject: "Biology",
    grade: 12,
    unit: "Evolution",
    difficulty: "easy",
    type: "definition",
    question: "Structures with a common evolutionary origin but different functions (e.g. a human arm and a whale flipper) are called:",
    options: { A: "Analogous structures", B: "Vestigial structures", C: "Homologous structures", D: "Convergent structures" },
    correct: "C",
    explanation: "Homologous structures share a common ancestral origin even when their functions differ.",
    source: "curated"
  },
  {
    id: "bio-g11-phys-001",
    subject: "Biology",
    grade: 11,
    unit: "Human body systems & physiology",
    difficulty: "easy",
    type: "definition",
    question: "Which blood vessels carry blood away from the heart?",
    options: { A: "Veins", B: "Arteries", C: "Capillaries", D: "Venules" },
    correct: "B",
    explanation: "Arteries carry blood away from the heart; veins return blood toward it.",
    source: "curated"
  },
  {
    id: "bio-g11-phys-002",
    subject: "Biology",
    grade: 11,
    unit: "Human body systems & physiology",
    difficulty: "easy",
    type: "definition",
    question: "The functional unit of the kidney is the:",
    options: { A: "Neuron", B: "Nephron", C: "Alveolus", D: "Villus" },
    correct: "B",
    explanation: "The nephron is the kidney's filtering unit that produces urine.",
    source: "curated"
  },
  {
    id: "bio-g11-phys-003",
    subject: "Biology",
    grade: 11,
    unit: "Human body systems & physiology",
    difficulty: "easy",
    type: "definition",
    question: "Which gas is taken into the blood at the alveoli of the lungs during breathing?",
    options: { A: "Carbon dioxide", B: "Nitrogen", C: "Oxygen", D: "Hydrogen" },
    correct: "C",
    explanation: "Oxygen diffuses from alveolar air into the blood, while carbon dioxide diffuses out.",
    source: "curated"
  },
  {
    id: "bio-g11-micro-001",
    subject: "Biology",
    grade: 11,
    unit: "Microorganisms",
    difficulty: "easy",
    type: "definition",
    question: "Which microorganism is used to make bread rise and to ferment alcohol?",
    options: { A: "Yeast", B: "Virus", C: "Algae", D: "Protozoan" },
    correct: "A",
    explanation: "Yeast (a fungus) ferments sugars, releasing CO₂ that makes dough rise and ethanol in brewing.",
    source: "curated"
  },
  {
    id: "bio-g11-micro-002",
    subject: "Biology",
    grade: 11,
    unit: "Microorganisms",
    difficulty: "easy",
    type: "conceptual",
    question: "Which of the following diseases is caused by a virus?",
    options: { A: "Tuberculosis", B: "Cholera", C: "Influenza", D: "Typhoid" },
    correct: "C",
    explanation: "Influenza (flu) is caused by a virus; tuberculosis, cholera and typhoid are bacterial diseases.",
    source: "curated"
  },
  {
    id: "bio-g12-energy-001",
    subject: "Biology",
    grade: 12,
    unit: "Energy transformation (photosynthesis/respiration)",
    difficulty: "easy",
    type: "definition",
    question: "In which organelle does photosynthesis take place?",
    options: { A: "Mitochondrion", B: "Chloroplast", C: "Nucleus", D: "Ribosome" },
    correct: "B",
    explanation: "Chloroplasts contain chlorophyll and carry out photosynthesis in plant cells.",
    source: "curated"
  },
  {
    id: "bio-g12-energy-002",
    subject: "Biology",
    grade: 12,
    unit: "Energy transformation (photosynthesis/respiration)",
    difficulty: "easy",
    type: "definition",
    question: "Which pigment absorbs light energy for photosynthesis?",
    options: { A: "Haemoglobin", B: "Melanin", C: "Chlorophyll", D: "Carotene only" },
    correct: "C",
    explanation: "Chlorophyll is the main pigment that absorbs light (mostly red and blue) to drive photosynthesis.",
    source: "curated"
  },
  {
    id: "bio-g12-energy-003",
    subject: "Biology",
    grade: 12,
    unit: "Energy transformation (photosynthesis/respiration)",
    difficulty: "easy",
    type: "conceptual",
    question: "What gas is released as a by-product of photosynthesis?",
    options: { A: "Carbon dioxide", B: "Oxygen", C: "Nitrogen", D: "Methane" },
    correct: "B",
    explanation: "Photosynthesis splits water and releases oxygen as a by-product while fixing CO₂ into sugar.",
    source: "curated"
  },
  {
    id: "bio-g12-eco-001",
    subject: "Biology",
    grade: 12,
    unit: "Ecology & population",
    difficulty: "easy",
    type: "definition",
    question: "Organisms that make their own food using sunlight are called:",
    options: { A: "Consumers", B: "Decomposers", C: "Producers", D: "Parasites" },
    correct: "C",
    explanation: "Producers (autotrophs) such as green plants synthesise their own food via photosynthesis.",
    source: "curated"
  },
  {
    id: "bio-g12-eco-002",
    subject: "Biology",
    grade: 12,
    unit: "Ecology & population",
    difficulty: "easy",
    type: "definition",
    question: "All the populations of different species living together in the same area form a:",
    options: { A: "Population", B: "Community", C: "Species", D: "Biome of one species" },
    correct: "B",
    explanation: "A community is all the interacting populations of different species in one area; a population is a single species.",
    source: "curated"
  },
  {
    id: "bio-g12-climate-001",
    subject: "Biology",
    grade: 12,
    unit: "Climate change",
    difficulty: "easy",
    type: "definition",
    question: "Which gas is the main contributor to the enhanced greenhouse effect from burning fossil fuels?",
    options: { A: "Oxygen", B: "Carbon dioxide", C: "Nitrogen", D: "Argon" },
    correct: "B",
    explanation: "Burning fossil fuels releases large amounts of carbon dioxide, the principal greenhouse gas driving warming.",
    source: "curated"
  },
  {
    id: "bio-g12-climate-002",
    subject: "Biology",
    grade: 12,
    unit: "Climate change",
    difficulty: "easy",
    type: "conceptual",
    question: "Which human activity most directly increases atmospheric carbon dioxide?",
    options: { A: "Planting trees", B: "Deforestation and burning coal", C: "Using solar panels", D: "Recycling paper" },
    correct: "B",
    explanation: "Burning coal releases CO₂ and deforestation removes the trees that absorb it, so both raise atmospheric CO₂.",
    source: "curated"
  },

  // ===================== MEDIUM (2-step reasoning / standard cross) =====================
  {
    id: "bio-g12-gen-005",
    subject: "Biology",
    grade: 12,
    unit: "Genetics (Mendelian crosses, DNA/inheritance)",
    difficulty: "medium",
    type: "calculation",
    question: "In a cross between two heterozygous tall pea plants (Tt × Tt), what fraction of offspring are expected to be short (tt)?",
    options: { A: "1/4", B: "1/2", C: "3/4", D: "0" },
    correct: "A",
    explanation: "Tt × Tt gives 1 TT : 2 Tt : 1 tt, so 1 of 4 offspring (1/4) is the homozygous recessive short type.",
    source: "curated"
  },
  {
    id: "bio-g12-gen-006",
    subject: "Biology",
    grade: 12,
    unit: "Genetics (Mendelian crosses, DNA/inheritance)",
    difficulty: "medium",
    type: "calculation",
    question: "A Tt × Tt monohybrid cross produces what phenotypic ratio of tall to short offspring?",
    options: { A: "1:1", B: "3:1", C: "9:3:3:1", D: "1:2:1" },
    correct: "B",
    explanation: "The 1 TT : 2 Tt : 1 tt genotype ratio gives 3 tall to 1 short, the classic 3:1 monohybrid phenotypic ratio.",
    source: "curated"
  },
  {
    id: "bio-g12-gen-007",
    subject: "Biology",
    grade: 12,
    unit: "Genetics (Mendelian crosses, DNA/inheritance)",
    difficulty: "medium",
    type: "calculation",
    question: "A test cross of a heterozygous purple-flowered plant (Pp) with a white-flowered plant (pp) gives what phenotypic ratio?",
    options: { A: "3 purple : 1 white", B: "1 purple : 1 white", C: "All purple", D: "All white" },
    correct: "B",
    explanation: "Pp × pp yields 1/2 Pp (purple) and 1/2 pp (white), a 1:1 ratio — the hallmark of a test cross.",
    source: "curated"
  },
  {
    id: "bio-g12-gen-008",
    subject: "Biology",
    grade: 12,
    unit: "Genetics (Mendelian crosses, DNA/inheritance)",
    difficulty: "medium",
    type: "calculation",
    question: "If one DNA strand reads 5'-ATGC-3', what is the sequence of the complementary strand (5'→3')?",
    options: { A: "5'-TACG-3'", B: "5'-GCAT-3'", C: "5'-CGTA-3'", D: "5'-ATGC-3'" },
    correct: "B",
    explanation: "Pair A–T and G–C antiparallel: the complement to 3'-TACG-5' read 5'→3' is GCAT.",
    source: "curated"
  },
  {
    id: "bio-g11-bioc-005",
    subject: "Biology",
    grade: 11,
    unit: "Biochemistry/enzymes",
    difficulty: "medium",
    type: "conceptual",
    question: "Why does an enzyme stop working (denature) at very high temperatures?",
    options: {
      A: "It runs out of substrate",
      B: "Its active site shape is destroyed as the protein unfolds",
      C: "It is converted into a carbohydrate",
      D: "The substrate becomes too cold"
    },
    correct: "B",
    explanation: "High heat breaks the bonds holding the protein's 3-D shape, distorting the active site so substrate no longer fits.",
    source: "curated"
  },
  {
    id: "bio-g11-bioc-006",
    subject: "Biology",
    grade: 11,
    unit: "Biochemistry/enzymes",
    difficulty: "medium",
    type: "conceptual",
    question: "As substrate concentration increases with a fixed amount of enzyme, the reaction rate eventually levels off because:",
    options: {
      A: "The enzyme is used up permanently",
      B: "All active sites become saturated with substrate",
      C: "The substrate denatures the enzyme",
      D: "The pH automatically rises"
    },
    correct: "B",
    explanation: "At saturation every active site is occupied, so adding more substrate cannot increase the rate until enzymes free up.",
    source: "curated"
  },
  {
    id: "bio-g11-bioc-007",
    subject: "Biology",
    grade: 11,
    unit: "Biochemistry/enzymes",
    difficulty: "medium",
    type: "conceptual",
    question: "The 'lock and key' model of enzyme action proposes that:",
    options: {
      A: "Any substrate fits any enzyme",
      B: "The active site has a shape complementary to one specific substrate",
      C: "Enzymes are permanently changed after the reaction",
      D: "Substrates break enzymes apart to react"
    },
    correct: "B",
    explanation: "The lock-and-key model explains enzyme specificity: only a substrate matching the active-site shape can bind.",
    source: "curated"
  },
  {
    id: "bio-g12-energy-004",
    subject: "Biology",
    grade: 12,
    unit: "Energy transformation (photosynthesis/respiration)",
    difficulty: "medium",
    type: "conceptual",
    question: "Which statement correctly distinguishes the light reactions of photosynthesis?",
    options: {
      A: "They occur in the stroma and fix CO₂",
      B: "They occur in the thylakoid membranes and produce ATP and NADPH",
      C: "They occur in mitochondria and make glucose",
      D: "They release CO₂ in the dark only"
    },
    correct: "B",
    explanation: "Light reactions happen in the thylakoid membranes, using light to make ATP and NADPH and to split water.",
    source: "curated"
  },
  {
    id: "bio-g12-energy-005",
    subject: "Biology",
    grade: 12,
    unit: "Energy transformation (photosynthesis/respiration)",
    difficulty: "medium",
    type: "conceptual",
    question: "The Calvin cycle (dark reactions) takes place in the ____ and uses ____ to fix carbon.",
    options: {
      A: "thylakoid; light directly",
      B: "stroma; ATP and NADPH",
      C: "mitochondrial matrix; oxygen",
      D: "cytoplasm; chlorophyll"
    },
    correct: "B",
    explanation: "The Calvin cycle runs in the stroma, consuming the ATP and NADPH made by the light reactions to fix CO₂ into sugar.",
    source: "curated"
  },
  {
    id: "bio-g12-energy-006",
    subject: "Biology",
    grade: 12,
    unit: "Energy transformation (photosynthesis/respiration)",
    difficulty: "medium",
    type: "conceptual",
    question: "During which stage of aerobic respiration is the most ATP produced?",
    options: { A: "Glycolysis", B: "Link reaction", C: "Krebs cycle", D: "Oxidative phosphorylation (electron transport chain)" },
    correct: "D",
    explanation: "Oxidative phosphorylation in the electron transport chain produces the bulk (about 34) of the ~38 ATP per glucose.",
    source: "curated"
  },
  {
    id: "bio-g12-energy-007",
    subject: "Biology",
    grade: 12,
    unit: "Energy transformation (photosynthesis/respiration)",
    difficulty: "medium",
    type: "conceptual",
    question: "In humans, anaerobic respiration in muscle cells converts glucose mainly into:",
    options: { A: "Ethanol and CO₂", B: "Lactic acid", C: "Carbon dioxide and water", D: "Glycogen" },
    correct: "B",
    explanation: "Without oxygen, human muscle uses glycolysis followed by fermentation to lactic acid, yielding only 2 ATP per glucose.",
    source: "curated"
  },
  {
    id: "bio-g11-cell-006",
    subject: "Biology",
    grade: 11,
    unit: "Cell biology",
    difficulty: "medium",
    type: "conceptual",
    question: "A red blood cell placed in pure (distilled) water will:",
    options: {
      A: "Shrink as water leaves it",
      B: "Swell and may burst as water enters by osmosis",
      C: "Stay exactly the same",
      D: "Turn into a plant cell"
    },
    correct: "B",
    explanation: "Water moves by osmosis from the dilute outside into the cell; lacking a wall, the animal cell swells and can lyse.",
    source: "curated"
  },
  {
    id: "bio-g11-cell-007",
    subject: "Biology",
    grade: 11,
    unit: "Cell biology",
    difficulty: "medium",
    type: "conceptual",
    question: "Movement of molecules from a region of high concentration to low concentration without using ATP is called:",
    options: { A: "Active transport", B: "Diffusion", C: "Endocytosis", D: "Exocytosis" },
    correct: "B",
    explanation: "Diffusion is passive movement down a concentration gradient and requires no cellular energy (ATP).",
    source: "curated"
  },
  {
    id: "bio-g11-cell-008",
    subject: "Biology",
    grade: 11,
    unit: "Cell biology",
    difficulty: "medium",
    type: "conceptual",
    question: "Which process produces two genetically identical daughter cells with the same chromosome number as the parent?",
    options: { A: "Meiosis", B: "Mitosis", C: "Fertilisation", D: "Binary fission of viruses" },
    correct: "B",
    explanation: "Mitosis yields two diploid daughter cells genetically identical to the parent; meiosis halves the chromosome number.",
    source: "curated"
  },
  {
    id: "bio-g11-phys-004",
    subject: "Biology",
    grade: 11,
    unit: "Human body systems & physiology",
    difficulty: "medium",
    type: "conceptual",
    question: "Which sequence correctly traces deoxygenated blood through the right side of the heart?",
    options: {
      A: "Left atrium → left ventricle → aorta",
      B: "Right atrium → right ventricle → pulmonary artery → lungs",
      C: "Right ventricle → aorta → body",
      D: "Pulmonary vein → right atrium → lungs"
    },
    correct: "B",
    explanation: "Deoxygenated blood enters the right atrium, passes to the right ventricle, and is pumped via the pulmonary artery to the lungs.",
    source: "curated"
  },
  {
    id: "bio-g11-phys-005",
    subject: "Biology",
    grade: 11,
    unit: "Human body systems & physiology",
    difficulty: "medium",
    type: "conceptual",
    question: "Insulin lowers blood glucose mainly by:",
    options: {
      A: "Breaking down glycogen into glucose",
      B: "Stimulating cells to take up glucose and store it as glycogen",
      C: "Increasing glucose absorption from food",
      D: "Stopping the kidney from filtering"
    },
    correct: "B",
    explanation: "Insulin from the pancreas promotes glucose uptake by cells and its storage as glycogen, reducing blood glucose.",
    source: "curated"
  },
  {
    id: "bio-g11-phys-006",
    subject: "Biology",
    grade: 11,
    unit: "Human body systems & physiology",
    difficulty: "medium",
    type: "conceptual",
    question: "The transmission of a nerve impulse along a neuron is mainly:",
    options: {
      A: "A mechanical push of fluid",
      B: "An electrochemical wave of membrane depolarisation",
      C: "A flow of blood",
      D: "Diffusion of oxygen"
    },
    correct: "B",
    explanation: "A nerve impulse is an action potential — a moving wave of membrane depolarisation driven by Na⁺ and K⁺ ion movement.",
    source: "curated"
  },
  {
    id: "bio-g12-evo-003",
    subject: "Biology",
    grade: 12,
    unit: "Evolution",
    difficulty: "medium",
    type: "conceptual",
    question: "Wings of a bird and wings of an insect perform the same function but have different origins. They are an example of:",
    options: { A: "Homologous structures", B: "Analogous structures", C: "Vestigial structures", D: "Genetic drift" },
    correct: "B",
    explanation: "Analogous structures share function but not ancestry; they result from convergent evolution, unlike homologous structures.",
    source: "curated"
  },
  {
    id: "bio-g12-evo-004",
    subject: "Biology",
    grade: 12,
    unit: "Evolution",
    difficulty: "medium",
    type: "conceptual",
    question: "The widespread survival of dark-coloured peppered moths on soot-darkened trees during industrialisation is an example of:",
    options: { A: "Lamarckian inheritance", B: "Natural selection", C: "Genetic engineering", D: "Random mutation with no effect" },
    correct: "B",
    explanation: "Camouflaged dark moths escaped predation and reproduced more, so selection by the environment shifted the population — natural selection.",
    source: "curated"
  },
  {
    id: "bio-g11-micro-003",
    subject: "Biology",
    grade: 11,
    unit: "Microorganisms",
    difficulty: "medium",
    type: "conceptual",
    question: "Why are antibiotics ineffective against viral infections such as the common cold?",
    options: {
      A: "Viruses are too large for antibiotics",
      B: "Viruses lack the bacterial structures and metabolism that antibiotics target",
      C: "Antibiotics only work in plants",
      D: "Viruses are immune by producing their own antibiotics"
    },
    correct: "B",
    explanation: "Antibiotics target bacterial processes like cell-wall synthesis; viruses have none of these and replicate inside host cells.",
    source: "curated"
  },
  {
    id: "bio-g11-micro-004",
    subject: "Biology",
    grade: 11,
    unit: "Microorganisms",
    difficulty: "medium",
    type: "conceptual",
    question: "In the nitrogen cycle, nitrogen-fixing bacteria in root nodules of legumes convert:",
    options: {
      A: "Nitrates into nitrogen gas",
      B: "Atmospheric nitrogen gas into ammonia/nitrogen compounds usable by plants",
      C: "Ammonia into oxygen",
      D: "Proteins into glucose"
    },
    correct: "B",
    explanation: "Nitrogen-fixing bacteria reduce inert N₂ gas into ammonia/usable nitrogen compounds, enriching the soil for plants.",
    source: "curated"
  },
  {
    id: "bio-g12-eco-003",
    subject: "Biology",
    grade: 12,
    unit: "Ecology & population",
    difficulty: "medium",
    type: "conceptual",
    question: "In a food chain: grass → grasshopper → frog → snake, the frog is a:",
    options: { A: "Primary producer", B: "Primary consumer", C: "Secondary consumer", D: "Decomposer" },
    correct: "C",
    explanation: "The grasshopper (primary consumer) eats grass; the frog eats the grasshopper, making it a secondary consumer.",
    source: "curated"
  },
  {
    id: "bio-g12-eco-004",
    subject: "Biology",
    grade: 12,
    unit: "Ecology & population",
    difficulty: "medium",
    type: "conceptual",
    question: "Two species competing for exactly the same limited resource in the same niche typically leads to:",
    options: {
      A: "Both increasing without limit",
      B: "One outcompeting or excluding the other (competitive exclusion)",
      C: "A predator–prey cycle",
      D: "Mutualism"
    },
    correct: "B",
    explanation: "The competitive exclusion principle states two species cannot coexist indefinitely on the identical limiting resource; one prevails.",
    source: "curated"
  },
  {
    id: "bio-g12-climate-003",
    subject: "Biology",
    grade: 12,
    unit: "Climate change",
    difficulty: "medium",
    type: "conceptual",
    question: "How do greenhouse gases warm the Earth?",
    options: {
      A: "They block sunlight from reaching the surface",
      B: "They absorb and re-emit outgoing infrared (heat) radiation, trapping energy",
      C: "They create a physical glass dome",
      D: "They increase the Sun's output"
    },
    correct: "B",
    explanation: "Greenhouse gases let sunlight in but absorb the infrared radiated by the warmed surface and re-emit it, trapping heat.",
    source: "curated"
  },
  {
    id: "bio-g12-climate-004",
    subject: "Biology",
    grade: 12,
    unit: "Climate change",
    difficulty: "medium",
    type: "conceptual",
    question: "Which is a likely ecological consequence of global warming?",
    options: {
      A: "Expansion of polar ice caps",
      B: "Rising sea levels and shifting species ranges",
      C: "A permanent drop in global temperatures",
      D: "Increased atmospheric oxygen from melting ice"
    },
    correct: "B",
    explanation: "Warming melts land ice and expands seawater, raising sea levels, and forces species to shift ranges toward cooler areas.",
    source: "curated"
  },

  // ===================== HARD (multi-step / combined concepts) =====================
  {
    id: "bio-g12-gen-009",
    subject: "Biology",
    grade: 12,
    unit: "Genetics (Mendelian crosses, DNA/inheritance)",
    difficulty: "hard",
    type: "calculation",
    question: "In a dihybrid cross RrYy × RrYy (round/yellow dominant), what fraction of offspring are round AND yellow (R_Y_)?",
    options: { A: "9/16", B: "3/16", C: "1/16", D: "1/4" },
    correct: "A",
    explanation: "The 9:3:3:1 dihybrid ratio gives 9/16 showing both dominant traits (round, yellow).",
    source: "curated"
  },
  {
    id: "bio-g12-gen-010",
    subject: "Biology",
    grade: 12,
    unit: "Genetics (Mendelian crosses, DNA/inheritance)",
    difficulty: "hard",
    type: "calculation",
    question: "From a dihybrid cross RrYy × RrYy, what fraction of offspring show both recessive traits (wrinkled and green, rryy)?",
    options: { A: "9/16", B: "3/16", C: "1/16", D: "1/8" },
    correct: "C",
    explanation: "Only the rryy class is fully recessive; in the 9:3:3:1 ratio it is 1/16 (1/4 rr × 1/4 yy).",
    source: "curated"
  },
  {
    id: "bio-g12-gen-011",
    subject: "Biology",
    grade: 12,
    unit: "Genetics (Mendelian crosses, DNA/inheritance)",
    difficulty: "hard",
    type: "calculation",
    question: "A colour-blind man (XᶜY) marries a woman who is a carrier (XᴬXᶜ). What is the probability that a son is colour-blind?",
    options: { A: "1/4", B: "1/2", C: "3/4", D: "1" },
    correct: "B",
    explanation: "Sons get Y from father and one X from mother; she gives Xᴬ or Xᶜ with equal chance, so 1/2 of sons (XᶜY) are colour-blind.",
    source: "curated"
  },
  {
    id: "bio-g12-gen-012",
    subject: "Biology",
    grade: 12,
    unit: "Genetics (Mendelian crosses, DNA/inheritance)",
    difficulty: "hard",
    type: "calculation",
    question: "Two parents are both blood group AB (genotype IᴬIᴮ). What proportion of their children are expected to be blood group AB?",
    options: { A: "1/4", B: "1/2", C: "3/4", D: "All" },
    correct: "B",
    explanation: "IᴬIᴮ × IᴬIᴮ gives 1 IᴬIᴬ (A) : 2 IᴬIᴮ (AB) : 1 IᴮIᴮ (B), so 2/4 = 1/2 are AB (codominance).",
    source: "curated"
  },
  {
    id: "bio-g12-gen-013",
    subject: "Biology",
    grade: 12,
    unit: "Genetics (Mendelian crosses, DNA/inheritance)",
    difficulty: "hard",
    type: "calculation",
    question: "In snapdragons, red (RR) × white (WW) gives all pink (RW) due to incomplete dominance. What phenotypic ratio results from crossing two pink plants (RW × RW)?",
    options: { A: "3 red : 1 white", B: "1 red : 2 pink : 1 white", C: "All pink", D: "1 red : 1 white" },
    correct: "B",
    explanation: "With incomplete dominance the heterozygote is pink, so RW × RW gives genotype 1:2:1, which is 1 red : 2 pink : 1 white phenotypically.",
    source: "curated"
  },
  {
    id: "bio-g12-energy-008",
    subject: "Biology",
    grade: 12,
    unit: "Energy transformation (photosynthesis/respiration)",
    difficulty: "hard",
    type: "calculation",
    question: "In the complete aerobic oxidation of one glucose molecule, glycolysis and the Krebs cycle together yield only a small net ATP directly. Approximately how many ATP come from oxidative phosphorylation out of the ~38 total?",
    options: { A: "About 2", B: "About 4", C: "About 34", D: "About 38" },
    correct: "C",
    explanation: "Substrate-level phosphorylation gives ~4 ATP (net 2 in glycolysis + 2 in Krebs); the remaining ~34 come from the electron transport chain.",
    source: "curated"
  },
  {
    id: "bio-g12-energy-009",
    subject: "Biology",
    grade: 12,
    unit: "Energy transformation (photosynthesis/respiration)",
    difficulty: "hard",
    type: "conceptual",
    question: "If a poison blocks the electron transport chain in mitochondria, why does ATP production fall sharply even though glycolysis still runs?",
    options: {
      A: "Glycolysis needs the chain to start",
      B: "Without the chain, NADH/FADH₂ are not re-oxidised, halting oxidative phosphorylation, the main ATP source",
      C: "Glucose can no longer enter the cell",
      D: "Oxygen is converted into glucose"
    },
    correct: "B",
    explanation: "Blocking the chain stops NADH/FADH₂ from being re-oxidised, so the proton gradient and oxidative phosphorylation collapse, removing ~90% of ATP.",
    source: "curated"
  },
  {
    id: "bio-g12-energy-010",
    subject: "Biology",
    grade: 12,
    unit: "Energy transformation (photosynthesis/respiration)",
    difficulty: "hard",
    type: "conceptual",
    question: "In the light reactions, the oxygen released by a plant comes from:",
    options: {
      A: "Carbon dioxide", B: "Glucose", C: "The splitting (photolysis) of water", D: "ATP breakdown"
    },
    correct: "C",
    explanation: "Photolysis splits water (H₂O) at photosystem II, supplying electrons and protons and releasing O₂; the CO₂ oxygen ends up in sugar, not O₂.",
    source: "curated"
  },
  {
    id: "bio-g11-bioc-008",
    subject: "Biology",
    grade: 11,
    unit: "Biochemistry/enzymes",
    difficulty: "hard",
    type: "conceptual",
    question: "A competitive inhibitor reduces enzyme activity, but adding a large excess of substrate restores the rate. This is because the inhibitor:",
    options: {
      A: "Binds the active site reversibly and competes with substrate",
      B: "Permanently denatures the enzyme",
      C: "Binds a site far from the active site and cannot be displaced",
      D: "Increases the substrate concentration"
    },
    correct: "A",
    explanation: "A competitive inhibitor binds the active site reversibly; flooding with substrate outcompetes it, so the maximum rate is regained.",
    source: "curated"
  },
  {
    id: "bio-g11-bioc-009",
    subject: "Biology",
    grade: 11,
    unit: "Biochemistry/enzymes",
    difficulty: "hard",
    type: "conceptual",
    question: "An enzyme has an optimum pH of 2 (as in the stomach). Placing it at pH 8 sharply lowers its activity mainly because:",
    options: {
      A: "Substrate concentration drops",
      B: "Changed charge interactions distort the active site, lowering substrate binding",
      C: "The enzyme is diluted",
      D: "Temperature automatically rises"
    },
    correct: "B",
    explanation: "Moving far from optimum pH alters the ionisation of side chains, disrupting bonds that maintain the active-site shape and reducing binding.",
    source: "curated"
  },
  {
    id: "bio-g11-cell-009",
    subject: "Biology",
    grade: 11,
    unit: "Cell biology",
    difficulty: "hard",
    type: "conceptual",
    question: "A plant cell placed in a strong salt solution becomes plasmolysed. This happens because:",
    options: {
      A: "Water enters the cell and bursts it",
      B: "Water leaves the cell by osmosis, so the membrane pulls away from the cell wall",
      C: "The cell wall dissolves",
      D: "Salt is actively pumped in, swelling the cell"
    },
    correct: "B",
    explanation: "In a hypertonic solution water leaves by osmosis; the protoplast shrinks and the membrane detaches from the wall — plasmolysis.",
    source: "curated"
  },
  {
    id: "bio-g11-cell-010",
    subject: "Biology",
    grade: 11,
    unit: "Cell biology",
    difficulty: "hard",
    type: "conceptual",
    question: "A diploid cell with 2n = 8 undergoes meiosis. How many chromosomes are in each resulting gamete, and how many gametes form from one cell?",
    options: {
      A: "8 chromosomes; 2 gametes",
      B: "4 chromosomes; 4 gametes",
      C: "16 chromosomes; 4 gametes",
      D: "4 chromosomes; 2 gametes"
    },
    correct: "B",
    explanation: "Meiosis halves the chromosome number (8 → 4) and one diploid cell produces four haploid gametes.",
    source: "curated"
  },
  {
    id: "bio-g11-phys-007",
    subject: "Biology",
    grade: 11,
    unit: "Human body systems & physiology",
    difficulty: "hard",
    type: "conceptual",
    question: "When blood glucose rises after a meal and then falls back to normal, this restoration is an example of:",
    options: {
      A: "Positive feedback amplifying the change",
      B: "Negative feedback restoring the set point",
      C: "Active transport across the gut",
      D: "Diffusion of glucose into bone"
    },
    correct: "B",
    explanation: "Insulin counters the rise and returns glucose toward the set point; correcting a deviation is negative feedback homeostasis.",
    source: "curated"
  },
  {
    id: "bio-g11-phys-008",
    subject: "Biology",
    grade: 11,
    unit: "Human body systems & physiology",
    difficulty: "hard",
    type: "conceptual",
    question: "In a kidney nephron, useful glucose that was filtered at the glomerulus is normally returned to the blood by:",
    options: {
      A: "Ultrafiltration in the glomerulus",
      B: "Selective reabsorption (active transport) in the proximal tubule",
      C: "Secretion in the collecting duct",
      D: "Osmosis in the loop of Henle only"
    },
    correct: "B",
    explanation: "Glucose is filtered but then completely reabsorbed by active transport in the proximal convoluted tubule, so healthy urine has no glucose.",
    source: "curated"
  },
  {
    id: "bio-g12-evo-005",
    subject: "Biology",
    grade: 12,
    unit: "Evolution",
    difficulty: "hard",
    type: "conceptual",
    question: "A small population is wiped out by a random flood, leaving survivors with allele frequencies different from the original by chance. This change is best described as:",
    options: { A: "Natural selection", B: "Genetic drift (bottleneck effect)", C: "Gene flow", D: "Directional mutation" },
    correct: "B",
    explanation: "Random loss of individuals (not based on fitness) that shifts allele frequencies in a small population is genetic drift — here a bottleneck.",
    source: "curated"
  },
  {
    id: "bio-g12-evo-006",
    subject: "Biology",
    grade: 12,
    unit: "Evolution",
    difficulty: "hard",
    type: "conceptual",
    question: "Overuse of antibiotics leads to resistant bacterial populations. The best evolutionary explanation is that antibiotics:",
    options: {
      A: "Cause bacteria to deliberately mutate to survive",
      B: "Select for pre-existing resistant variants, which then reproduce and dominate",
      C: "Teach bacteria to become resistant during their lifetime",
      D: "Make all bacteria immortal"
    },
    correct: "B",
    explanation: "Random mutations create some resistant bacteria; the antibiotic kills the susceptible ones, so resistant survivors reproduce — selection, not directed change.",
    source: "curated"
  },
  {
    id: "bio-g11-micro-005",
    subject: "Biology",
    grade: 11,
    unit: "Microorganisms",
    difficulty: "hard",
    type: "conceptual",
    question: "A vaccine protects against a disease primarily by:",
    options: {
      A: "Killing the pathogen directly with antibiotics in the injection",
      B: "Exposing the immune system to a harmless antigen so memory cells form for a fast future response",
      C: "Providing the body with ready-made glucose",
      D: "Replacing the patient's white blood cells"
    },
    correct: "B",
    explanation: "A vaccine presents antigens that trigger an immune response and memory cells, so a later real infection is destroyed quickly.",
    source: "curated"
  },
  {
    id: "bio-g11-micro-006",
    subject: "Biology",
    grade: 11,
    unit: "Microorganisms",
    difficulty: "hard",
    type: "calculation",
    question: "A bacterium divides by binary fission every 20 minutes. Starting from one cell, how many bacteria are present after 2 hours (ideal conditions)?",
    options: { A: "6", B: "12", C: "64", D: "120" },
    correct: "C",
    explanation: "2 hours = 120 min = 6 divisions; 1 × 2⁶ = 64 bacteria.",
    source: "curated"
  },
  {
    id: "bio-g12-eco-005",
    subject: "Biology",
    grade: 12,
    unit: "Ecology & population",
    difficulty: "hard",
    type: "calculation",
    question: "If producers in an ecosystem capture 10,000 kJ of energy and only ~10% transfers between trophic levels, roughly how much energy reaches the secondary consumers?",
    options: { A: "1000 kJ", B: "100 kJ", C: "10 kJ", D: "5000 kJ" },
    correct: "B",
    explanation: "Producers 10,000 → primary consumers 1000 (10%) → secondary consumers 100 kJ (10% of 1000).",
    source: "curated"
  },
  {
    id: "bio-g12-eco-006",
    subject: "Biology",
    grade: 12,
    unit: "Ecology & population",
    difficulty: "hard",
    type: "conceptual",
    question: "Why are food chains rarely longer than four or five trophic levels?",
    options: {
      A: "Predators refuse to eat more than four times",
      B: "About 90% of energy is lost at each level, so little remains to support higher levels",
      C: "There are not enough species names",
      D: "Decomposers stop the chain at level four"
    },
    correct: "B",
    explanation: "Only ~10% of energy passes up each level, so after several transfers too little energy remains to sustain another level.",
    source: "curated"
  },
  {
    id: "bio-g12-climate-005",
    subject: "Biology",
    grade: 12,
    unit: "Climate change",
    difficulty: "hard",
    type: "conceptual",
    question: "Large-scale deforestation contributes to climate change by BOTH:",
    options: {
      A: "Releasing stored carbon when trees are burned and removing a CO₂-absorbing carbon sink",
      B: "Increasing photosynthesis and cooling the planet",
      C: "Producing more oxygen and less CO₂",
      D: "Reducing rainfall only, with no effect on carbon"
    },
    correct: "A",
    explanation: "Burning/clearing forests releases their stored carbon as CO₂ and simultaneously removes the trees that would have absorbed atmospheric CO₂.",
    source: "curated"
  },
  {
    id: "bio-g12-climate-006",
    subject: "Biology",
    grade: 12,
    unit: "Climate change",
    difficulty: "hard",
    type: "conceptual",
    question: "Melting Arctic sea ice can accelerate warming through a positive feedback because:",
    options: {
      A: "Open dark ocean absorbs more sunlight than reflective ice, warming further and melting more ice",
      B: "Ice melting cools the surrounding water permanently",
      C: "Less ice means more CO₂ is absorbed by the sea",
      D: "Melting ice blocks sunlight"
    },
    correct: "A",
    explanation: "Ice reflects sunlight (high albedo); when it melts, darker ocean absorbs more heat, causing more melting — a self-reinforcing positive feedback.",
    source: "curated"
  },

  // ===================== IMPOSSIBLE (synthesis / subtle traps) =====================
  {
    id: "bio-g12-gen-014",
    subject: "Biology",
    grade: 12,
    unit: "Genetics (Mendelian crosses, DNA/inheritance)",
    difficulty: "impossible",
    type: "calculation",
    question: "In a trihybrid cross AaBbCc × AaBbCc (all independently assorting, simple dominance), what fraction of offspring are homozygous recessive at all three loci (aabbcc)?",
    options: { A: "1/8", B: "1/16", C: "1/32", D: "1/64" },
    correct: "D",
    explanation: "Each locus gives 1/4 homozygous recessive; independent assortment multiplies: (1/4)³ = 1/64.",
    source: "curated"
  },
  {
    id: "bio-g12-gen-015",
    subject: "Biology",
    grade: 12,
    unit: "Genetics (Mendelian crosses, DNA/inheritance)",
    difficulty: "impossible",
    type: "calculation",
    question: "In a dihybrid cross AaBb × AaBb, what fraction of offspring are heterozygous at BOTH genes (AaBb)?",
    options: { A: "1/16", B: "1/8", C: "1/4", D: "9/16" },
    correct: "C",
    explanation: "P(Aa) = 1/2 and P(Bb) = 1/2; independent, so P(AaBb) = 1/2 × 1/2 = 1/4 (the 4 of 16 double-heterozygotes).",
    source: "curated"
  },
  {
    id: "bio-g12-gen-016",
    subject: "Biology",
    grade: 12,
    unit: "Genetics (Mendelian crosses, DNA/inheritance)",
    difficulty: "impossible",
    type: "calculation",
    question: "Two parents are heterozygous for an autosomal recessive disease (Aa × Aa). Given that a child is unaffected (shows the dominant phenotype), what is the probability that this child is a carrier (Aa)?",
    options: { A: "1/2", B: "1/4", C: "2/3", D: "3/4" },
    correct: "C",
    explanation: "Aa × Aa gives 1 AA : 2 Aa : 1 aa; among the 3 unaffected (AA, Aa, Aa), 2 are carriers, so the conditional probability is 2/3.",
    source: "curated"
  },
  {
    id: "bio-g12-gen-017",
    subject: "Biology",
    grade: 12,
    unit: "Genetics (Mendelian crosses, DNA/inheritance)",
    difficulty: "impossible",
    type: "calculation",
    question: "In sweet peas, two gene pairs control flower colour: at least one dominant allele at BOTH genes (C_P_) gives purple, otherwise white (complementary gene interaction). What purple:white ratio results from CcPp × CcPp?",
    options: { A: "9 purple : 7 white", B: "9 purple : 3 : 3 : 1", C: "3 purple : 1 white", D: "13 purple : 3 white" },
    correct: "A",
    explanation: "Only the 9/16 C_P_ class is purple; the 3 + 3 + 1 = 7/16 lacking a dominant at either gene are white, giving the 9:7 epistatic ratio.",
    source: "curated"
  },
  {
    id: "bio-g12-gen-018",
    subject: "Biology",
    grade: 12,
    unit: "Genetics (Mendelian crosses, DNA/inheritance)",
    difficulty: "impossible",
    type: "calculation",
    question: "Two genes are linked 20 map units apart. A dihybrid AaBb (cis arrangement, AB/ab) is test-crossed with aabb. What percentage of offspring are recombinant?",
    options: { A: "10%", B: "20%", C: "40%", D: "50%" },
    correct: "B",
    explanation: "Map distance equals percent recombination, so 20 map units means 20% recombinant offspring (10% each recombinant class).",
    source: "curated"
  },
  {
    id: "bio-g12-energy-011",
    subject: "Biology",
    grade: 12,
    unit: "Energy transformation (photosynthesis/respiration)",
    difficulty: "impossible",
    type: "conceptual",
    question: "A scientist supplies a plant with water labelled with heavy oxygen (H₂¹⁸O) but normal CO₂. Where does the ¹⁸O label first appear?",
    options: {
      A: "In the glucose produced",
      B: "In the oxygen gas (O₂) released",
      C: "In the carbon dioxide taken up",
      D: "In the ATP phosphate groups"
    },
    correct: "B",
    explanation: "Photolysis splits water, so the released O₂ comes from water; therefore the ¹⁸O label appears in the evolved oxygen gas, not in glucose.",
    source: "curated"
  },
  {
    id: "bio-g12-energy-012",
    subject: "Biology",
    grade: 12,
    unit: "Energy transformation (photosynthesis/respiration)",
    difficulty: "impossible",
    type: "conceptual",
    question: "A chemical makes the inner mitochondrial membrane freely permeable to protons (an 'uncoupler'). The immediate effect is that the cell:",
    options: {
      A: "Makes more ATP than normal",
      B: "Continues electron transport and oxygen use but makes little ATP, releasing energy as heat",
      C: "Stops glycolysis entirely",
      D: "Begins photosynthesis"
    },
    correct: "B",
    explanation: "An uncoupler dissipates the proton gradient, so ATP synthase has no gradient to drive it; electron transport and O₂ use continue but energy is lost as heat.",
    source: "curated"
  },
  {
    id: "bio-g12-energy-013",
    subject: "Biology",
    grade: 12,
    unit: "Energy transformation (photosynthesis/respiration)",
    difficulty: "impossible",
    type: "conceptual",
    question: "Both oxidative phosphorylation in mitochondria and the light reactions in chloroplasts share which core mechanism for making ATP?",
    options: {
      A: "Direct transfer of a phosphate from glucose",
      B: "Chemiosmosis: a proton gradient across a membrane drives ATP synthase",
      C: "Fixation of carbon dioxide",
      D: "Breakdown of lactic acid"
    },
    correct: "B",
    explanation: "Both use chemiosmosis — an electron transport chain pumps protons to form a gradient whose flow through ATP synthase makes ATP.",
    source: "curated"
  },
  {
    id: "bio-g11-bioc-010",
    subject: "Biology",
    grade: 11,
    unit: "Biochemistry/enzymes",
    difficulty: "impossible",
    type: "conceptual",
    question: "An enzyme is studied with a non-competitive inhibitor. Compared with no inhibitor, the maximum rate (Vmax) and the substrate level for half-maximal rate (Km) change how?",
    options: {
      A: "Vmax decreases; Km unchanged",
      B: "Vmax unchanged; Km increases",
      C: "Vmax increases; Km decreases",
      D: "Both Vmax and Km increase"
    },
    correct: "A",
    explanation: "A non-competitive inhibitor binds away from the active site and cannot be outcompeted, so Vmax falls while substrate affinity (Km) is unchanged.",
    source: "curated"
  },
  {
    id: "bio-g11-bioc-011",
    subject: "Biology",
    grade: 11,
    unit: "Biochemistry/enzymes",
    difficulty: "impossible",
    type: "conceptual",
    question: "In a metabolic pathway A→B→C→D, the end product D binds the first enzyme and slows it. This feedback inhibition is most precisely an example of:",
    options: {
      A: "Competitive inhibition at the active site for substrate A",
      B: "Allosteric (end-product) inhibition regulating pathway flux",
      C: "Denaturation of enzyme 1",
      D: "Substrate-level phosphorylation"
    },
    correct: "B",
    explanation: "The product binds a regulatory (allosteric) site on the first enzyme, throttling the whole pathway — classic allosteric feedback inhibition.",
    source: "curated"
  },
  {
    id: "bio-g11-cell-011",
    subject: "Biology",
    grade: 11,
    unit: "Cell biology",
    difficulty: "impossible",
    type: "conceptual",
    question: "A drug stops microtubule spindle fibres from functioning during cell division. The most direct consequence is that cells:",
    options: {
      A: "Cannot replicate their DNA in S phase",
      B: "Arrest in mitosis because chromosomes cannot be separated to the poles",
      C: "Skip mitosis and divide faster",
      D: "Stop making proteins"
    },
    correct: "B",
    explanation: "Spindle microtubules pull sister chromatids apart in anaphase; blocking them halts cells in mitosis with chromosomes unable to segregate.",
    source: "curated"
  },
  {
    id: "bio-g11-cell-012",
    subject: "Biology",
    grade: 11,
    unit: "Cell biology",
    difficulty: "impossible",
    type: "conceptual",
    question: "Mitochondria and chloroplasts have their own circular DNA and double membranes. This is the central evidence for which idea?",
    options: {
      A: "Spontaneous generation",
      B: "The endosymbiotic theory (they descend from engulfed prokaryotes)",
      C: "That they are made by the Golgi",
      D: "That they are viruses"
    },
    correct: "B",
    explanation: "Their prokaryote-like circular DNA, ribosomes and double membrane support endosymbiosis: ancestral cells engulfed bacteria that became these organelles.",
    source: "curated"
  },
  {
    id: "bio-g11-phys-009",
    subject: "Biology",
    grade: 11,
    unit: "Human body systems & physiology",
    difficulty: "impossible",
    type: "conceptual",
    question: "At high altitude with low oxygen, the body increases red blood cell production over weeks. The correct hormonal pathway is:",
    options: {
      A: "Insulin from the pancreas stimulates bone marrow",
      B: "Low oxygen triggers the kidneys to release erythropoietin, stimulating bone marrow to make red cells",
      C: "The lungs directly manufacture red blood cells",
      D: "Adrenaline destroys old cells to free oxygen"
    },
    correct: "B",
    explanation: "Sensing low O₂, the kidneys secrete erythropoietin (EPO), which stimulates bone marrow to produce more red blood cells, raising oxygen-carrying capacity.",
    source: "curated"
  },
  {
    id: "bio-g11-phys-010",
    subject: "Biology",
    grade: 11,
    unit: "Human body systems & physiology",
    difficulty: "impossible",
    type: "conceptual",
    question: "During heavy exercise, why does CO₂ rising in the blood increase the breathing rate even before oxygen drops much?",
    options: {
      A: "CO₂ is directly toxic to the lungs",
      B: "CO₂ forms carbonic acid, lowering blood pH; chemoreceptors detect this and signal faster breathing",
      C: "CO₂ binds haemoglobin better than O₂ and suffocates cells",
      D: "Muscles store CO₂ as glycogen"
    },
    correct: "B",
    explanation: "Dissolved CO₂ forms carbonic acid, lowering pH; chemoreceptors detect the acidity and drive the respiratory centre to increase breathing to expel CO₂.",
    source: "curated"
  },
  {
    id: "bio-g12-evo-007",
    subject: "Biology",
    grade: 12,
    unit: "Evolution",
    difficulty: "impossible",
    type: "calculation",
    question: "In a population at Hardy–Weinberg equilibrium, the recessive disorder affects 1 in 100 people (q² = 0.01). What fraction of the population are carriers (heterozygotes)?",
    options: { A: "0.10", B: "0.18", C: "0.81", D: "0.01" },
    correct: "B",
    explanation: "q = 0.1, p = 0.9; carrier frequency 2pq = 2(0.9)(0.1) = 0.18, i.e. 18% of the population.",
    source: "curated"
  },
  {
    id: "bio-g12-evo-008",
    subject: "Biology",
    grade: 12,
    unit: "Evolution",
    difficulty: "impossible",
    type: "conceptual",
    question: "A single mountain range splits one beetle species into two groups that, over time, can no longer interbreed. This is best described as:",
    options: {
      A: "Sympatric speciation", B: "Allopatric speciation by geographic isolation", C: "Convergent evolution", D: "Artificial selection"
    },
    correct: "B",
    explanation: "A physical barrier geographically isolates populations, which then diverge until reproductively incompatible — allopatric speciation.",
    source: "curated"
  },
  {
    id: "bio-g11-micro-007",
    subject: "Biology",
    grade: 11,
    unit: "Microorganisms",
    difficulty: "impossible",
    type: "conceptual",
    question: "A retrovirus like HIV is unusual because it:",
    options: {
      A: "Has no genetic material",
      B: "Uses reverse transcriptase to copy its RNA into DNA that integrates into the host genome",
      C: "Is a type of bacterium with a nucleus",
      D: "Reproduces only outside living cells"
    },
    correct: "B",
    explanation: "Retroviruses carry RNA and the enzyme reverse transcriptase, which makes DNA from that RNA; the DNA then inserts into the host's chromosomes.",
    source: "curated"
  },
  {
    id: "bio-g11-micro-008",
    subject: "Biology",
    grade: 11,
    unit: "Microorganisms",
    difficulty: "impossible",
    type: "conceptual",
    question: "Decomposer bacteria are essential to ecosystems mainly because they:",
    options: {
      A: "Add new energy to the ecosystem",
      B: "Recycle nutrients by breaking dead matter into inorganic forms that producers can reuse",
      C: "Photosynthesise to feed consumers",
      D: "Fix all the carbon dioxide in the air"
    },
    correct: "B",
    explanation: "Decomposers release locked-up nutrients (N, P, etc.) from dead organisms back into the soil/water for producers; energy still flows in only from the Sun.",
    source: "curated"
  },
  {
    id: "bio-g12-eco-007",
    subject: "Biology",
    grade: 12,
    unit: "Ecology & population",
    difficulty: "impossible",
    type: "calculation",
    question: "A population of 500 has a per-capita birth rate of 0.30/year and death rate of 0.10/year, with no migration. What is the population's growth (number added) in one year under exponential growth?",
    options: { A: "50", B: "100", C: "150", D: "200" },
    correct: "B",
    explanation: "Growth rate r = 0.30 − 0.10 = 0.20/yr; ΔN = rN = 0.20 × 500 = 100 individuals added.",
    source: "curated"
  },
  {
    id: "bio-g12-eco-008",
    subject: "Biology",
    grade: 12,
    unit: "Ecology & population",
    difficulty: "impossible",
    type: "conceptual",
    question: "Why do persistent toxins like DDT reach their highest concentrations in top predators (biomagnification)?",
    options: {
      A: "Top predators produce the toxin themselves",
      B: "The toxin is not excreted and accumulates, becoming more concentrated at each higher trophic level",
      C: "Producers absorb most of the toxin and pass none on",
      D: "Toxins are diluted as they move up the chain"
    },
    correct: "B",
    explanation: "Fat-soluble toxins resist excretion, so each consumer accumulates the toxin from all its prey, concentrating it further at every trophic level.",
    source: "curated"
  },
  {
    id: "bio-g12-climate-007",
    subject: "Biology",
    grade: 12,
    unit: "Climate change",
    difficulty: "impossible",
    type: "conceptual",
    question: "Ocean acidification, a consequence of rising CO₂, harms coral and shellfish because dissolved CO₂:",
    options: {
      A: "Raises seawater pH, dissolving plankton",
      B: "Forms carbonic acid that lowers pH and reduces carbonate ions needed to build calcium carbonate shells",
      C: "Adds oxygen that corrodes shells",
      D: "Heats the water so shells melt"
    },
    correct: "B",
    explanation: "CO₂ dissolves to form carbonic acid, lowering pH and depleting carbonate ions, so organisms struggle to build/maintain their CaCO₃ shells and skeletons.",
    source: "curated"
  },
  {
    id: "bio-g12-climate-008",
    subject: "Biology",
    grade: 12,
    unit: "Climate change",
    difficulty: "impossible",
    type: "conceptual",
    question: "Thawing permafrost is considered a dangerous climate feedback mainly because it:",
    options: {
      A: "Reflects more sunlight back to space",
      B: "Releases stored methane and CO₂, greenhouse gases that cause further warming and more thawing",
      C: "Absorbs atmospheric CO₂ permanently",
      D: "Cools the Arctic by exposing soil"
    },
    correct: "B",
    explanation: "Frozen soil holds vast organic carbon; thawing lets microbes release methane and CO₂, intensifying warming that thaws still more permafrost — a positive feedback.",
    source: "curated"
  }
];
