window.BANK_MATH = [
  // ===================== EASY (single-step recall / one-line substitution) =====================
  {
    id: "math-g12-func-001",
    subject: "Mathematics",
    grade: 12,
    unit: "Functions & relations",
    difficulty: "easy",
    type: "calculation",
    question: "If f(x) = 3x − 5, what is f(4)?",
    options: { A: "7", B: "12", C: "17", D: "−2" },
    correct: "A",
    explanation: "Substitute x = 4: f(4) = 3(4) − 5 = 12 − 5 = 7.",
    source: "curated"
  },
  {
    id: "math-g12-func-002",
    subject: "Mathematics",
    grade: 12,
    unit: "Functions & relations",
    difficulty: "easy",
    type: "calculation",
    question: "If f(x) = x² + 1, what is f(−3)?",
    options: { A: "−8", B: "10", C: "8", D: "−10" },
    correct: "B",
    explanation: "f(−3) = (−3)² + 1 = 9 + 1 = 10.",
    source: "curated"
  },
  {
    id: "math-g12-func-003",
    subject: "Mathematics",
    grade: 12,
    unit: "Functions & relations",
    difficulty: "easy",
    type: "conceptual",
    question: "What is the domain of f(x) = 1/(x − 2)?",
    options: { A: "All real numbers", B: "All real numbers except x = 0", C: "All real numbers except x = 2", D: "x ≥ 2" },
    correct: "C",
    explanation: "The denominator x − 2 cannot be 0, so x ≠ 2; all other reals are allowed.",
    source: "curated"
  },
  {
    id: "math-g12-rat-001",
    subject: "Mathematics",
    grade: 12,
    unit: "Rational expressions",
    difficulty: "easy",
    type: "calculation",
    question: "Simplify: (x² − 9)/(x − 3), for x ≠ 3.",
    options: { A: "x − 3", B: "x + 3", C: "x² − 3", D: "x + 9" },
    correct: "B",
    explanation: "x² − 9 = (x − 3)(x + 3); cancel (x − 3) to get x + 3.",
    source: "curated"
  },
  {
    id: "math-g12-rat-002",
    subject: "Mathematics",
    grade: 12,
    unit: "Rational expressions",
    difficulty: "easy",
    type: "calculation",
    question: "Simplify: (2/3) + (1/6).",
    options: { A: "3/9", B: "1/2", C: "5/6", D: "3/6" },
    correct: "C",
    explanation: "Common denominator 6: 4/6 + 1/6 = 5/6.",
    source: "curated"
  },
  {
    id: "math-g12-mat-001",
    subject: "Mathematics",
    grade: 12,
    unit: "Matrices & determinants",
    difficulty: "easy",
    type: "calculation",
    question: "What is the determinant of the matrix [[2, 3], [1, 4]]?",
    options: { A: "5", B: "11", C: "8", D: "−5" },
    correct: "A",
    explanation: "For [[a,b],[c,d]], det = ad − bc = (2)(4) − (3)(1) = 8 − 3 = 5.",
    source: "curated"
  },
  {
    id: "math-g12-mat-002",
    subject: "Mathematics",
    grade: 12,
    unit: "Matrices & determinants",
    difficulty: "easy",
    type: "calculation",
    question: "If A = [[1, 2], [0, 3]] and B = [[4, 0], [1, 2]], what is the (1,1) entry of A + B?",
    options: { A: "5", B: "4", C: "1", D: "6" },
    correct: "A",
    explanation: "Matrix addition is entrywise: (1,1) entry = 1 + 4 = 5.",
    source: "curated"
  },
  {
    id: "math-g12-vec-001",
    subject: "Mathematics",
    grade: 12,
    unit: "Vectors",
    difficulty: "easy",
    type: "calculation",
    question: "What is the magnitude of the vector v = (3, 4)?",
    options: { A: "7", B: "5", C: "25", D: "1" },
    correct: "B",
    explanation: "|v| = √(3² + 4²) = √(9 + 16) = √25 = 5.",
    source: "curated"
  },
  {
    id: "math-g12-vec-002",
    subject: "Mathematics",
    grade: 12,
    unit: "Vectors",
    difficulty: "easy",
    type: "calculation",
    question: "Given a = (1, 2) and b = (3, −1), find a + b.",
    options: { A: "(4, 1)", B: "(−2, 3)", C: "(4, −1)", D: "(3, −2)" },
    correct: "A",
    explanation: "Add componentwise: (1 + 3, 2 + (−1)) = (4, 1).",
    source: "curated"
  },
  {
    id: "math-g12-vec-003",
    subject: "Mathematics",
    grade: 12,
    unit: "Vectors",
    difficulty: "easy",
    type: "calculation",
    question: "What is the dot product of a = (2, 3) and b = (1, 4)?",
    options: { A: "14", B: "5", C: "11", D: "10" },
    correct: "A",
    explanation: "a·b = (2)(1) + (3)(4) = 2 + 12 = 14.",
    source: "curated"
  },
  {
    id: "math-g12-seq-001",
    subject: "Mathematics",
    grade: 12,
    unit: "Sequences & series",
    difficulty: "easy",
    type: "calculation",
    question: "In an arithmetic sequence with first term 3 and common difference 4, what is the 5th term?",
    options: { A: "19", B: "23", C: "15", D: "20" },
    correct: "A",
    explanation: "aₙ = a₁ + (n−1)d = 3 + (5−1)(4) = 3 + 16 = 19.",
    source: "curated"
  },
  {
    id: "math-g12-seq-002",
    subject: "Mathematics",
    grade: 12,
    unit: "Sequences & series",
    difficulty: "easy",
    type: "calculation",
    question: "In a geometric sequence with first term 2 and common ratio 3, what is the 3rd term?",
    options: { A: "18", B: "12", C: "6", D: "54" },
    correct: "A",
    explanation: "aₙ = a₁·r^(n−1) = 2·3² = 2·9 = 18.",
    source: "curated"
  },
  {
    id: "math-g12-calc-001",
    subject: "Mathematics",
    grade: 12,
    unit: "Introduction to calculus",
    difficulty: "easy",
    type: "calculation",
    question: "What is the derivative of f(x) = x³?",
    options: { A: "3x²", B: "x²", C: "3x", D: "x⁴/4" },
    correct: "A",
    explanation: "By the power rule d/dx(xⁿ) = n·xⁿ⁻¹, so d/dx(x³) = 3x².",
    source: "curated"
  },
  {
    id: "math-g12-calc-002",
    subject: "Mathematics",
    grade: 12,
    unit: "Introduction to calculus",
    difficulty: "easy",
    type: "calculation",
    question: "Evaluate the limit: lim (x→2) (x² + 1).",
    options: { A: "5", B: "4", C: "3", D: "6" },
    correct: "A",
    explanation: "The function is continuous, so substitute x = 2: 2² + 1 = 5.",
    source: "curated"
  },
  {
    id: "math-g12-calc-003",
    subject: "Mathematics",
    grade: 12,
    unit: "Introduction to calculus",
    difficulty: "easy",
    type: "calculation",
    question: "What is ∫ 2x dx?",
    options: { A: "x² + C", B: "2x² + C", C: "2 + C", D: "x²/2 + C" },
    correct: "A",
    explanation: "∫ xⁿ dx = xⁿ⁺¹/(n+1); ∫ 2x dx = 2·(x²/2) + C = x² + C.",
    source: "curated"
  },
  {
    id: "math-g12-stat-001",
    subject: "Mathematics",
    grade: 12,
    unit: "Statistics",
    difficulty: "easy",
    type: "calculation",
    question: "What is the mean of the data set 4, 8, 6, 10, 2?",
    options: { A: "6", B: "5", C: "7", D: "8" },
    correct: "A",
    explanation: "Mean = (4 + 8 + 6 + 10 + 2)/5 = 30/5 = 6.",
    source: "curated"
  },
  {
    id: "math-g12-stat-002",
    subject: "Mathematics",
    grade: 12,
    unit: "Statistics",
    difficulty: "easy",
    type: "calculation",
    question: "What is the range of the data set 12, 7, 19, 5, 15?",
    options: { A: "14", B: "12", C: "19", D: "5" },
    correct: "A",
    explanation: "Range = maximum − minimum = 19 − 5 = 14.",
    source: "curated"
  },
  {
    id: "math-g12-stat-003",
    subject: "Mathematics",
    grade: 12,
    unit: "Statistics",
    difficulty: "easy",
    type: "calculation",
    question: "What is the median of the data set 3, 9, 1, 7, 5?",
    options: { A: "5", B: "7", C: "1", D: "9" },
    correct: "A",
    explanation: "Sort: 1, 3, 5, 7, 9. The middle value (3rd of 5) is 5.",
    source: "curated"
  },
  {
    id: "math-g12-prob-001",
    subject: "Mathematics",
    grade: 12,
    unit: "Probability & combinatorics",
    difficulty: "easy",
    type: "calculation",
    question: "A fair six-sided die is rolled once. What is the probability of getting an even number?",
    options: { A: "1/2", B: "1/3", C: "1/6", D: "2/3" },
    correct: "A",
    explanation: "Even outcomes are 2, 4, 6 (3 of 6), so P = 3/6 = 1/2.",
    source: "curated"
  },
  {
    id: "math-g12-prob-002",
    subject: "Mathematics",
    grade: 12,
    unit: "Probability & combinatorics",
    difficulty: "easy",
    type: "calculation",
    question: "What is the value of 5! (5 factorial)?",
    options: { A: "120", B: "25", C: "60", D: "20" },
    correct: "A",
    explanation: "5! = 5·4·3·2·1 = 120.",
    source: "curated"
  },
  {
    id: "math-g12-trig-001",
    subject: "Mathematics",
    grade: 12,
    unit: "Trigonometry",
    difficulty: "easy",
    type: "calculation",
    question: "What is the value of sin 30°?",
    options: { A: "1/2", B: "√3/2", C: "1", D: "√2/2" },
    correct: "A",
    explanation: "sin 30° = 1/2 is a standard exact value.",
    source: "curated"
  },
  {
    id: "math-g12-trig-002",
    subject: "Mathematics",
    grade: 12,
    unit: "Trigonometry",
    difficulty: "easy",
    type: "calculation",
    question: "What is the value of cos 60°?",
    options: { A: "1/2", B: "√3/2", C: "0", D: "1" },
    correct: "A",
    explanation: "cos 60° = 1/2 is a standard exact value.",
    source: "curated"
  },
  {
    id: "math-g12-trig-003",
    subject: "Mathematics",
    grade: 12,
    unit: "Trigonometry",
    difficulty: "easy",
    type: "calculation",
    question: "What is the value of tan 45°?",
    options: { A: "1", B: "0", C: "√3", D: "1/√3" },
    correct: "A",
    explanation: "tan 45° = sin 45°/cos 45° = (√2/2)/(√2/2) = 1.",
    source: "curated"
  },
  {
    id: "math-g12-solid-001",
    subject: "Mathematics",
    grade: 12,
    unit: "Solid geometry",
    difficulty: "easy",
    type: "calculation",
    question: "What is the volume of a cube with edge length 4 cm?",
    options: { A: "64 cm³", B: "16 cm³", C: "12 cm³", D: "48 cm³" },
    correct: "A",
    explanation: "Volume of a cube = s³ = 4³ = 64 cm³.",
    source: "curated"
  },
  {
    id: "math-g12-absineq-001",
    subject: "Mathematics",
    grade: 12,
    unit: "Absolute-value inequalities",
    difficulty: "easy",
    type: "calculation",
    question: "What is the value of |−7|?",
    options: { A: "7", B: "−7", C: "0", D: "14" },
    correct: "A",
    explanation: "The absolute value of −7 is its distance from 0, which is 7.",
    source: "curated"
  },
  {
    id: "math-g12-absineq-002",
    subject: "Mathematics",
    grade: 12,
    unit: "Absolute-value inequalities",
    difficulty: "easy",
    type: "conceptual",
    question: "The solution set of |x| < 3 is:",
    options: { A: "−3 < x < 3", B: "x < 3", C: "x > 3 or x < −3", D: "x > −3" },
    correct: "A",
    explanation: "|x| < 3 means x is within 3 units of 0, i.e. −3 < x < 3.",
    source: "curated"
  },
  {
    id: "math-g12-tran-001",
    subject: "Mathematics",
    grade: 12,
    unit: "Transformations",
    difficulty: "easy",
    type: "conceptual",
    question: "Reflecting the point (3, 5) across the x-axis gives:",
    options: { A: "(3, −5)", B: "(−3, 5)", C: "(−3, −5)", D: "(5, 3)" },
    correct: "A",
    explanation: "Reflection across the x-axis keeps x and negates y: (3, 5) → (3, −5).",
    source: "curated"
  },
  {
    id: "math-g12-tran-002",
    subject: "Mathematics",
    grade: 12,
    unit: "Transformations",
    difficulty: "easy",
    type: "conceptual",
    question: "Translating the point (2, 1) by the vector (3, −4) gives:",
    options: { A: "(5, −3)", B: "(−1, 5)", C: "(5, 5)", D: "(6, −4)" },
    correct: "A",
    explanation: "Add the translation vector: (2 + 3, 1 + (−4)) = (5, −3).",
    source: "curated"
  },
  {
    id: "math-g12-linprog-001",
    subject: "Mathematics",
    grade: 12,
    unit: "Linear programming",
    difficulty: "easy",
    type: "calculation",
    question: "For the objective function P = 2x + 3y, what is P at the point (4, 1)?",
    options: { A: "11", B: "9", C: "14", D: "7" },
    correct: "A",
    explanation: "P = 2(4) + 3(1) = 8 + 3 = 11.",
    source: "curated"
  },
  {
    id: "math-g12-func-004",
    subject: "Mathematics",
    grade: 12,
    unit: "Functions & relations",
    difficulty: "easy",
    type: "conceptual",
    question: "Which of these relations is a function of x?",
    options: { A: "y = 2x + 1", B: "x = y²", C: "x² + y² = 4", D: "|y| = x" },
    correct: "A",
    explanation: "A function assigns exactly one y to each x; only y = 2x + 1 passes the vertical-line test.",
    source: "curated"
  },
  {
    id: "math-g12-calc-004",
    subject: "Mathematics",
    grade: 12,
    unit: "Introduction to calculus",
    difficulty: "easy",
    type: "calculation",
    question: "What is the derivative of f(x) = 7?",
    options: { A: "0", B: "7", C: "1", D: "7x" },
    correct: "A",
    explanation: "The derivative of any constant is 0.",
    source: "curated"
  },

  // ===================== MEDIUM (2-step reasoning / standard formula applied once) =====================
  {
    id: "math-g12-prob-003",
    subject: "Mathematics",
    grade: 12,
    unit: "Probability & combinatorics",
    difficulty: "medium",
    type: "calculation",
    question: "What is the coefficient of x⁶y⁴ in the expansion of (x + y)¹⁰?",
    options: { A: "210", B: "120", C: "252", D: "45" },
    correct: "A",
    explanation: "The coefficient is C(10, 4) = 10!/(4!·6!) = 210.",
    source: "curated"
  },
  {
    id: "math-g12-solid-002",
    subject: "Mathematics",
    grade: 12,
    unit: "Solid geometry",
    difficulty: "medium",
    type: "calculation",
    question: "A cylinder has radius 3 cm and height 7 cm. What is its volume? (use π)",
    options: { A: "63π cm³", B: "21π cm³", C: "147π cm³", D: "42π cm³" },
    correct: "A",
    explanation: "V = πr²h = π(3²)(7) = π(9)(7) = 63π cm³.",
    source: "curated"
  },
  {
    id: "math-g12-mat-003",
    subject: "Mathematics",
    grade: 12,
    unit: "Matrices & determinants",
    difficulty: "medium",
    type: "calculation",
    question: "What is the determinant of [[3, 0, 2], [0, 1, 0], [4, 0, 5]]?",
    options: { A: "7", B: "23", C: "15", D: "−7" },
    correct: "A",
    explanation: "Expand along the middle row: only the (2,2) entry 1 contributes: 1·det[[3,2],[4,5]] = 1·(15 − 8) = 7.",
    source: "curated"
  },
  {
    id: "math-g12-seq-003",
    subject: "Mathematics",
    grade: 12,
    unit: "Sequences & series",
    difficulty: "medium",
    type: "calculation",
    question: "What is the sum of the first 10 terms of the arithmetic series 2 + 5 + 8 + …?",
    options: { A: "155", B: "145", C: "165", D: "150" },
    correct: "A",
    explanation: "Sₙ = n/2·(2a + (n−1)d) = 10/2·(2·2 + 9·3) = 5·(4 + 27) = 5·31 = 155.",
    source: "curated"
  },
  {
    id: "math-g12-seq-004",
    subject: "Mathematics",
    grade: 12,
    unit: "Sequences & series",
    difficulty: "medium",
    type: "calculation",
    question: "What is the sum to infinity of the geometric series 8 + 4 + 2 + 1 + …?",
    options: { A: "16", B: "15", C: "32", D: "12" },
    correct: "A",
    explanation: "For |r| < 1, S∞ = a/(1 − r) = 8/(1 − 1/2) = 8/(1/2) = 16.",
    source: "curated"
  },
  {
    id: "math-g12-calc-005",
    subject: "Mathematics",
    grade: 12,
    unit: "Introduction to calculus",
    difficulty: "medium",
    type: "calculation",
    question: "What is the derivative of f(x) = 4x³ − 2x² + 5x − 1?",
    options: { A: "12x² − 4x + 5", B: "12x² − 4x + 5x", C: "4x² − 2x + 5", D: "12x² − 2x + 5" },
    correct: "A",
    explanation: "Differentiate termwise: 12x² − 4x + 5; the constant −1 differentiates to 0.",
    source: "curated"
  },
  {
    id: "math-g12-calc-006",
    subject: "Mathematics",
    grade: 12,
    unit: "Introduction to calculus",
    difficulty: "medium",
    type: "calculation",
    question: "Evaluate ∫₀¹ 3x² dx.",
    options: { A: "1", B: "3", C: "1/3", D: "2" },
    correct: "A",
    explanation: "∫ 3x² dx = x³; evaluate from 0 to 1: 1³ − 0³ = 1.",
    source: "curated"
  },
  {
    id: "math-g12-calc-007",
    subject: "Mathematics",
    grade: 12,
    unit: "Introduction to calculus",
    difficulty: "medium",
    type: "calculation",
    question: "Evaluate the limit: lim (x→3) (x² − 9)/(x − 3).",
    options: { A: "6", B: "0", C: "3", D: "undefined" },
    correct: "A",
    explanation: "Factor: (x² − 9)/(x − 3) = (x + 3) for x ≠ 3; substituting x = 3 gives 6.",
    source: "curated"
  },
  {
    id: "math-g12-trig-004",
    subject: "Mathematics",
    grade: 12,
    unit: "Trigonometry",
    difficulty: "medium",
    type: "calculation",
    question: "If sin θ = 3/5 and θ is acute, what is cos θ?",
    options: { A: "4/5", B: "5/4", C: "3/4", D: "5/3" },
    correct: "A",
    explanation: "cos²θ = 1 − sin²θ = 1 − 9/25 = 16/25, so cos θ = 4/5 (positive since θ is acute).",
    source: "curated"
  },
  {
    id: "math-g12-trig-005",
    subject: "Mathematics",
    grade: 12,
    unit: "Trigonometry",
    difficulty: "medium",
    type: "calculation",
    question: "Simplify: sin²θ + cos²θ + tan 0°.",
    options: { A: "1", B: "0", C: "2", D: "1 + tan θ" },
    correct: "A",
    explanation: "By the identity sin²θ + cos²θ = 1, and tan 0° = 0, so the total is 1 + 0 = 1.",
    source: "curated"
  },
  {
    id: "math-g12-rat-003",
    subject: "Mathematics",
    grade: 12,
    unit: "Rational expressions",
    difficulty: "medium",
    type: "calculation",
    question: "Simplify: (x² − 4)/(x² + 4x + 4), for x ≠ −2.",
    options: { A: "(x − 2)/(x + 2)", B: "(x + 2)/(x − 2)", C: "x − 2", D: "(x − 4)/(x + 4)" },
    correct: "A",
    explanation: "x² − 4 = (x − 2)(x + 2) and x² + 4x + 4 = (x + 2)²; cancel one (x + 2): (x − 2)/(x + 2).",
    source: "curated"
  },
  {
    id: "math-g12-rat-004",
    subject: "Mathematics",
    grade: 12,
    unit: "Rational expressions",
    difficulty: "medium",
    type: "calculation",
    question: "Solve for x: 3/(x − 1) = 6.",
    options: { A: "3/2", B: "2", C: "1/2", D: "3" },
    correct: "A",
    explanation: "Cross-multiply: 3 = 6(x − 1) → 3 = 6x − 6 → 6x = 9 → x = 3/2.",
    source: "curated"
  },
  {
    id: "math-g12-stat-004",
    subject: "Mathematics",
    grade: 12,
    unit: "Statistics",
    difficulty: "medium",
    type: "calculation",
    question: "What is the variance of the data set 2, 4, 6 (population variance)?",
    options: { A: "8/3", B: "2", C: "4", D: "8" },
    correct: "A",
    explanation: "Mean = 4; squared deviations: 4, 0, 4; variance = (4 + 0 + 4)/3 = 8/3.",
    source: "curated"
  },
  {
    id: "math-g12-stat-005",
    subject: "Mathematics",
    grade: 12,
    unit: "Statistics",
    difficulty: "medium",
    type: "calculation",
    question: "The population variance of a data set is 49. What is its standard deviation?",
    options: { A: "7", B: "24.5", C: "49", D: "2401" },
    correct: "A",
    explanation: "Standard deviation = √variance = √49 = 7.",
    source: "curated"
  },
  {
    id: "math-g12-vec-004",
    subject: "Mathematics",
    grade: 12,
    unit: "Vectors",
    difficulty: "medium",
    type: "calculation",
    question: "Vectors a = (2, k) and b = (3, 6) are parallel. What is k?",
    options: { A: "4", B: "9", C: "3", D: "2" },
    correct: "A",
    explanation: "Parallel vectors satisfy 2/3 = k/6, so k = 12/3 = 4.",
    source: "curated"
  },
  {
    id: "math-g12-vec-005",
    subject: "Mathematics",
    grade: 12,
    unit: "Vectors",
    difficulty: "medium",
    type: "calculation",
    question: "Vectors a = (2, 3) and b = (k, 4) are perpendicular. What is k?",
    options: { A: "−6", B: "6", C: "−2", D: "2" },
    correct: "A",
    explanation: "Perpendicular means a·b = 0: 2k + 12 = 0 → k = −6.",
    source: "curated"
  },
  {
    id: "math-g12-absineq-003",
    subject: "Mathematics",
    grade: 12,
    unit: "Absolute-value inequalities",
    difficulty: "medium",
    type: "calculation",
    question: "Solve: |2x − 1| ≤ 5.",
    options: { A: "−2 ≤ x ≤ 3", B: "x ≤ 3", C: "−3 ≤ x ≤ 2", D: "x ≥ −2" },
    correct: "A",
    explanation: "−5 ≤ 2x − 1 ≤ 5 → −4 ≤ 2x ≤ 6 → −2 ≤ x ≤ 3.",
    source: "curated"
  },
  {
    id: "math-g12-absineq-004",
    subject: "Mathematics",
    grade: 12,
    unit: "Absolute-value inequalities",
    difficulty: "medium",
    type: "calculation",
    question: "Solve: |x + 2| > 4.",
    options: { A: "x < −6 or x > 2", B: "−6 < x < 2", C: "x > 2", D: "x < −6" },
    correct: "A",
    explanation: "|x + 2| > 4 gives x + 2 > 4 or x + 2 < −4, i.e. x > 2 or x < −6.",
    source: "curated"
  },
  {
    id: "math-g12-tran-003",
    subject: "Mathematics",
    grade: 12,
    unit: "Transformations",
    difficulty: "medium",
    type: "conceptual",
    question: "The point (4, 2) is rotated 90° counterclockwise about the origin. Its image is:",
    options: { A: "(−2, 4)", B: "(2, −4)", C: "(−4, −2)", D: "(2, 4)" },
    correct: "A",
    explanation: "A 90° counterclockwise rotation maps (x, y) → (−y, x), so (4, 2) → (−2, 4).",
    source: "curated"
  },
  {
    id: "math-g12-tran-004",
    subject: "Mathematics",
    grade: 12,
    unit: "Transformations",
    difficulty: "medium",
    type: "conceptual",
    question: "Under a dilation centered at the origin with scale factor 3, the point (2, −1) maps to:",
    options: { A: "(6, −3)", B: "(5, 2)", C: "(2/3, −1/3)", D: "(−6, 3)" },
    correct: "A",
    explanation: "A dilation by factor 3 multiplies both coordinates by 3: (2·3, −1·3) = (6, −3).",
    source: "curated"
  },
  {
    id: "math-g12-func-005",
    subject: "Mathematics",
    grade: 12,
    unit: "Functions & relations",
    difficulty: "medium",
    type: "calculation",
    question: "If f(x) = 2x + 1 and g(x) = x², what is (f ∘ g)(3), i.e. f(g(3))?",
    options: { A: "19", B: "49", C: "13", D: "37" },
    correct: "A",
    explanation: "g(3) = 9, then f(9) = 2(9) + 1 = 19.",
    source: "curated"
  },
  {
    id: "math-g12-func-006",
    subject: "Mathematics",
    grade: 12,
    unit: "Functions & relations",
    difficulty: "medium",
    type: "calculation",
    question: "If f(x) = (x − 3)/2, what is its inverse f⁻¹(x)?",
    options: { A: "2x + 3", B: "2x − 3", C: "(x + 3)/2", D: "x/2 + 3" },
    correct: "A",
    explanation: "Set y = (x − 3)/2, swap and solve: x = (y − 3)/2 → 2x = y − 3 → y = 2x + 3.",
    source: "curated"
  },
  {
    id: "math-g12-prob-004",
    subject: "Mathematics",
    grade: 12,
    unit: "Probability & combinatorics",
    difficulty: "medium",
    type: "calculation",
    question: "In how many ways can 3 students be chosen from a group of 7?",
    options: { A: "35", B: "21", C: "210", D: "343" },
    correct: "A",
    explanation: "C(7, 3) = 7!/(3!·4!) = (7·6·5)/(3·2·1) = 35.",
    source: "curated"
  },
  {
    id: "math-g12-prob-005",
    subject: "Mathematics",
    grade: 12,
    unit: "Probability & combinatorics",
    difficulty: "medium",
    type: "calculation",
    question: "Two fair dice are rolled. What is the probability that the sum is 7?",
    options: { A: "1/6", B: "1/12", C: "7/36", D: "1/9" },
    correct: "A",
    explanation: "There are 6 favorable pairs ((1,6)…(6,1)) of 36, so P = 6/36 = 1/6.",
    source: "curated"
  },
  {
    id: "math-g12-linprog-002",
    subject: "Mathematics",
    grade: 12,
    unit: "Linear programming",
    difficulty: "medium",
    type: "calculation",
    question: "Maximize P = 3x + 2y over the corner points (0,0), (4,0), (0,3), (2,2). What is the maximum?",
    options: { A: "12", B: "10", C: "6", D: "13" },
    correct: "A",
    explanation: "Evaluate P: (0,0)→0, (4,0)→12, (0,3)→6, (2,2)→10. The maximum is 12 at (4,0).",
    source: "curated"
  },
  {
    id: "math-g12-mat-004",
    subject: "Mathematics",
    grade: 12,
    unit: "Matrices & determinants",
    difficulty: "medium",
    type: "calculation",
    question: "What is the (1,1) entry of the product [[1, 2], [3, 4]]·[[5, 6], [7, 8]]?",
    options: { A: "19", B: "23", C: "26", D: "43" },
    correct: "A",
    explanation: "(1,1) = row 1 · column 1 = (1)(5) + (2)(7) = 5 + 14 = 19.",
    source: "curated"
  },
  {
    id: "math-g12-solid-003",
    subject: "Mathematics",
    grade: 12,
    unit: "Solid geometry",
    difficulty: "medium",
    type: "calculation",
    question: "What is the volume of a cone with radius 3 cm and height 4 cm? (use π)",
    options: { A: "12π cm³", B: "36π cm³", C: "24π cm³", D: "48π cm³" },
    correct: "A",
    explanation: "V = (1/3)πr²h = (1/3)π(9)(4) = 12π cm³.",
    source: "curated"
  },
  {
    id: "math-g12-seq-005",
    subject: "Mathematics",
    grade: 12,
    unit: "Sequences & series",
    difficulty: "medium",
    type: "calculation",
    question: "An arithmetic sequence has a₃ = 11 and a₇ = 27. What is the common difference?",
    options: { A: "4", B: "8", C: "5", D: "3" },
    correct: "A",
    explanation: "a₇ − a₃ = 4d = 27 − 11 = 16, so d = 4.",
    source: "curated"
  },

  // ===================== HARD (multi-step / combines concepts / careful algebra) =====================
  {
    id: "math-g12-prob-006",
    subject: "Mathematics",
    grade: 12,
    unit: "Probability & combinatorics",
    difficulty: "hard",
    type: "calculation",
    question: "What is the coefficient of x² in the expansion of (2x − 1)⁵?",
    options: { A: "−40", B: "40", C: "−80", D: "80" },
    correct: "A",
    explanation: "The x² term is C(5,2)(2x)²(−1)³ = 10·4x²·(−1) = −40x², so the coefficient is −40.",
    source: "curated"
  },
  {
    id: "math-g12-prob-007",
    subject: "Mathematics",
    grade: 12,
    unit: "Probability & combinatorics",
    difficulty: "hard",
    type: "calculation",
    question: "A biased coin has P(head) = 0.4. In 5 independent tosses, what is the probability of exactly 2 heads?",
    options: { A: "0.3456", B: "0.2304", C: "0.4000", D: "0.1296" },
    correct: "A",
    explanation: "P = C(5,2)(0.4)²(0.6)³ = 10·0.16·0.216 = 0.3456.",
    source: "curated"
  },
  {
    id: "math-g12-solid-004",
    subject: "Mathematics",
    grade: 12,
    unit: "Solid geometry",
    difficulty: "hard",
    type: "calculation",
    question: "A frustum of a cone has height h = 6, lower radius R = 5 and upper radius r = 3. Using V = (πh/3)(R² + Rr + r²), what is its volume?",
    options: { A: "98π", B: "49π", C: "294π", D: "147π" },
    correct: "A",
    explanation: "V = (π·6/3)(25 + 15 + 9) = 2π·49 = 98π.",
    source: "curated"
  },
  {
    id: "math-g12-calc-008",
    subject: "Mathematics",
    grade: 12,
    unit: "Introduction to calculus",
    difficulty: "hard",
    type: "calculation",
    question: "Find the x-coordinate of the local maximum of f(x) = x³ − 3x.",
    options: { A: "−1", B: "1", C: "0", D: "3" },
    correct: "A",
    explanation: "f′(x) = 3x² − 3 = 0 → x = ±1; f″(x) = 6x, and f″(−1) = −6 < 0, so x = −1 is a local maximum.",
    source: "curated"
  },
  {
    id: "math-g12-calc-009",
    subject: "Mathematics",
    grade: 12,
    unit: "Introduction to calculus",
    difficulty: "hard",
    type: "calculation",
    question: "What is the derivative of f(x) = (2x + 1)(x² − 3)?",
    options: { A: "6x² + 2x − 6", B: "6x² − 6", C: "4x² + 2x − 6", D: "6x² + 2x + 6" },
    correct: "A",
    explanation: "Product rule: 2(x² − 3) + (2x + 1)(2x) = 2x² − 6 + 4x² + 2x = 6x² + 2x − 6.",
    source: "curated"
  },
  {
    id: "math-g12-calc-010",
    subject: "Mathematics",
    grade: 12,
    unit: "Introduction to calculus",
    difficulty: "hard",
    type: "calculation",
    question: "Evaluate ∫₁² (2x + 1/x²) dx.",
    options: { A: "7/2", B: "3", C: "9/2", D: "4" },
    correct: "A",
    explanation: "Antiderivative: x² − 1/x. At 2: 4 − 1/2 = 7/2; at 1: 1 − 1 = 0; difference = 7/2.",
    source: "curated"
  },
  {
    id: "math-g12-mat-005",
    subject: "Mathematics",
    grade: 12,
    unit: "Matrices & determinants",
    difficulty: "hard",
    type: "calculation",
    question: "What is the determinant of [[1, 2, 3], [4, 5, 6], [7, 8, 10]]?",
    options: { A: "−3", B: "0", C: "3", D: "−6" },
    correct: "A",
    explanation: "Expand: 1(5·10 − 6·8) − 2(4·10 − 6·7) + 3(4·8 − 5·7) = 1(50−48) − 2(40−42) + 3(32−35) = 2 + 4 − 9 = −3.",
    source: "curated"
  },
  {
    id: "math-g12-seq-006",
    subject: "Mathematics",
    grade: 12,
    unit: "Sequences & series",
    difficulty: "hard",
    type: "calculation",
    question: "The 2nd term of a geometric sequence is 6 and the 5th term is 48. What is the first term?",
    options: { A: "3", B: "2", C: "6", D: "12" },
    correct: "A",
    explanation: "a₅/a₂ = r³ = 48/6 = 8, so r = 2; then a₁ = a₂/r = 6/2 = 3.",
    source: "curated"
  },
  {
    id: "math-g12-seq-007",
    subject: "Mathematics",
    grade: 12,
    unit: "Sequences & series",
    difficulty: "hard",
    type: "calculation",
    question: "What is the sum Σ (from k=1 to 20) of (3k − 2)?",
    options: { A: "590", B: "610", C: "570", D: "600" },
    correct: "A",
    explanation: "Σ(3k − 2) = 3·Σk − 2·20 = 3·(20·21/2) − 40 = 3·210 − 40 = 630 − 40 = 590.",
    source: "curated"
  },
  {
    id: "math-g12-trig-006",
    subject: "Mathematics",
    grade: 12,
    unit: "Trigonometry",
    difficulty: "hard",
    type: "calculation",
    question: "Solve for x in [0°, 360°): 2 sin x − 1 = 0.",
    options: { A: "30° and 150°", B: "30° and 210°", C: "60° and 120°", D: "45° and 135°" },
    correct: "A",
    explanation: "sin x = 1/2; in [0°, 360°) the solutions are x = 30° and x = 150°.",
    source: "curated"
  },
  {
    id: "math-g12-trig-007",
    subject: "Mathematics",
    grade: 12,
    unit: "Trigonometry",
    difficulty: "hard",
    type: "calculation",
    question: "If cos 2θ = 1 − 2sin²θ and sin θ = 0.6, what is cos 2θ?",
    options: { A: "0.28", B: "0.64", C: "0.72", D: "0.36" },
    correct: "A",
    explanation: "cos 2θ = 1 − 2(0.6)² = 1 − 2(0.36) = 1 − 0.72 = 0.28.",
    source: "curated"
  },
  {
    id: "math-g12-rat-005",
    subject: "Mathematics",
    grade: 12,
    unit: "Rational expressions",
    difficulty: "hard",
    type: "calculation",
    question: "Simplify: 1/(x − 1) − 1/(x + 1) as a single fraction.",
    options: { A: "2/(x² − 1)", B: "0", C: "2x/(x² − 1)", D: "−2/(x² − 1)" },
    correct: "A",
    explanation: "Common denominator (x−1)(x+1) = x²−1: [(x+1) − (x−1)]/(x²−1) = 2/(x²−1).",
    source: "curated"
  },
  {
    id: "math-g12-absineq-005",
    subject: "Mathematics",
    grade: 12,
    unit: "Absolute-value inequalities",
    difficulty: "hard",
    type: "calculation",
    question: "Solve: |3x − 2| < |x + 4|.",
    options: { A: "−1/2 < x < 3", B: "x < 3", C: "−3 < x < 1/2", D: "x > −1/2" },
    correct: "A",
    explanation: "Square both sides: (3x−2)² < (x+4)² → 9x²−12x+4 < x²+8x+16 → 8x²−20x−12 < 0 → 2x²−5x−3 < 0 → (2x+1)(x−3) < 0 → −1/2 < x < 3.",
    source: "curated"
  },
  {
    id: "math-g12-vec-006",
    subject: "Mathematics",
    grade: 12,
    unit: "Vectors",
    difficulty: "hard",
    type: "calculation",
    question: "What is the angle between a = (1, 0) and b = (1, √3)?",
    options: { A: "60°", B: "30°", C: "45°", D: "90°" },
    correct: "A",
    explanation: "cos θ = (a·b)/(|a||b|) = 1/(1·2) = 1/2, so θ = 60°.",
    source: "curated"
  },
  {
    id: "math-g12-func-007",
    subject: "Mathematics",
    grade: 12,
    unit: "Functions & relations",
    difficulty: "hard",
    type: "calculation",
    question: "The quadratic f(x) = x² − 6x + 11 has its minimum value at:",
    options: { A: "2", B: "11", C: "−3", D: "5" },
    correct: "A",
    explanation: "Vertex x = −b/2a = 6/2 = 3; minimum value f(3) = 9 − 18 + 11 = 2.",
    source: "curated"
  },
  {
    id: "math-g12-func-008",
    subject: "Mathematics",
    grade: 12,
    unit: "Functions & relations",
    difficulty: "hard",
    type: "calculation",
    question: "For what value of k does x² + kx + 9 = 0 have exactly one (repeated) real root?",
    options: { A: "k = ±6", B: "k = 6 only", C: "k = ±3", D: "k = 9" },
    correct: "A",
    explanation: "One repeated root needs discriminant 0: k² − 4(1)(9) = 0 → k² = 36 → k = ±6.",
    source: "curated"
  },
  {
    id: "math-g12-stat-006",
    subject: "Mathematics",
    grade: 12,
    unit: "Statistics",
    difficulty: "hard",
    type: "calculation",
    question: "What is the interquartile range (IQR) of: 2, 4, 6, 8, 10, 12, 14, 16 (Q1 and Q3 by median-of-halves)?",
    options: { A: "8", B: "7", C: "6", D: "10" },
    correct: "A",
    explanation: "Lower half 2,4,6,8 → Q1 = (4+6)/2 = 5; upper half 10,12,14,16 → Q3 = (12+14)/2 = 13; IQR = 13 − 5 = 8.",
    source: "curated"
  },
  {
    id: "math-g12-stat-007",
    subject: "Mathematics",
    grade: 12,
    unit: "Statistics",
    difficulty: "hard",
    type: "calculation",
    question: "A data set of 4 values has mean 10. Three of the values are 8, 11, and 9. What is the fourth value?",
    options: { A: "12", B: "10", C: "14", D: "9" },
    correct: "A",
    explanation: "Total = mean·n = 10·4 = 40; fourth = 40 − (8 + 11 + 9) = 40 − 28 = 12.",
    source: "curated"
  },
  {
    id: "math-g12-linprog-003",
    subject: "Mathematics",
    grade: 12,
    unit: "Linear programming",
    difficulty: "hard",
    type: "calculation",
    question: "Maximize P = 4x + 5y subject to x + y ≤ 8, x ≤ 5, x ≥ 0, y ≥ 0. What is the maximum value?",
    options: { A: "40", B: "37", C: "32", D: "41" },
    correct: "A",
    explanation: "Corner points: (0,0)→0, (5,0)→20, (5,3)→35, (0,8)→40. The maximum is 40 at (0,8).",
    source: "curated"
  },
  {
    id: "math-g12-tran-005",
    subject: "Mathematics",
    grade: 12,
    unit: "Transformations",
    difficulty: "hard",
    type: "calculation",
    question: "The point (3, 1) is rotated 180° about the origin, then reflected across the y-axis. Its final image is:",
    options: { A: "(3, −1)", B: "(−3, −1)", C: "(−3, 1)", D: "(1, 3)" },
    correct: "A",
    explanation: "180° rotation: (3,1) → (−3,−1); reflection across y-axis negates x: (−3,−1) → (3,−1).",
    source: "curated"
  },
  {
    id: "math-g12-prob-008",
    subject: "Mathematics",
    grade: 12,
    unit: "Probability & combinatorics",
    difficulty: "hard",
    type: "calculation",
    question: "From a bag with 4 red and 6 blue balls, two are drawn without replacement. What is the probability both are red?",
    options: { A: "2/15", B: "4/25", C: "1/5", D: "6/45" },
    correct: "A",
    explanation: "P = (4/10)·(3/9) = 12/90 = 2/15.",
    source: "curated"
  },
  {
    id: "math-g12-calc-011",
    subject: "Mathematics",
    grade: 12,
    unit: "Introduction to calculus",
    difficulty: "hard",
    type: "calculation",
    question: "What is the equation of the tangent line to y = x² at x = 3?",
    options: { A: "y = 6x − 9", B: "y = 6x + 9", C: "y = 3x − 9", D: "y = 9x − 6" },
    correct: "A",
    explanation: "y′ = 2x, slope at x = 3 is 6; point (3, 9): y − 9 = 6(x − 3) → y = 6x − 9.",
    source: "curated"
  },

  // ===================== IMPOSSIBLE (olympiad-adjacent, multi-concept synthesis) =====================
  {
    id: "math-g12-prob-009",
    subject: "Mathematics",
    grade: 12,
    unit: "Probability & combinatorics",
    difficulty: "impossible",
    type: "calculation",
    question: "What is the term independent of x in the expansion of (x² + 1/x)⁶?",
    options: { A: "15", B: "20", C: "6", D: "1" },
    correct: "A",
    explanation: "General term C(6,k)(x²)^(6−k)(1/x)^k = C(6,k)x^(12−3k); set 12 − 3k = 0 → k = 4; C(6,4) = 15.",
    source: "curated"
  },
  {
    id: "math-g12-calc-012",
    subject: "Mathematics",
    grade: 12,
    unit: "Introduction to calculus",
    difficulty: "impossible",
    type: "calculation",
    question: "Evaluate the limit: lim (x→0) (sin 3x)/(2x).",
    options: { A: "3/2", B: "1/2", C: "3", D: "0" },
    correct: "A",
    explanation: "(sin 3x)/(2x) = (3/2)·(sin 3x)/(3x); since (sin 3x)/(3x) → 1, the limit is 3/2.",
    source: "curated"
  },
  {
    id: "math-g12-calc-013",
    subject: "Mathematics",
    grade: 12,
    unit: "Introduction to calculus",
    difficulty: "impossible",
    type: "calculation",
    question: "A 10 m ladder slides down a wall. When the base is 6 m from the wall and moving away at 2 m/s, how fast is the top sliding down?",
    options: { A: "1.5 m/s", B: "2 m/s", C: "8/3 m/s", D: "0.75 m/s" },
    correct: "A",
    explanation: "x² + y² = 100; y = 8 when x = 6. Differentiate: 2x(dx/dt) + 2y(dy/dt) = 0 → dy/dt = −(x/y)(dx/dt) = −(6/8)(2) = −1.5, so 1.5 m/s downward.",
    source: "curated"
  },
  {
    id: "math-g12-seq-008",
    subject: "Mathematics",
    grade: 12,
    unit: "Sequences & series",
    difficulty: "impossible",
    type: "calculation",
    question: "Evaluate the infinite sum Σ (from n=1 to ∞) of n/2ⁿ.",
    options: { A: "2", B: "1", C: "3/2", D: "4" },
    correct: "A",
    explanation: "For |x| < 1, Σ n·xⁿ = x/(1−x)²; with x = 1/2: (1/2)/(1/2)² = (1/2)/(1/4) = 2.",
    source: "curated"
  },
  {
    id: "math-g12-mat-006",
    subject: "Mathematics",
    grade: 12,
    unit: "Matrices & determinants",
    difficulty: "impossible",
    type: "calculation",
    question: "If A is a 3×3 matrix with det(A) = 4, what is det(2A)?",
    options: { A: "32", B: "8", C: "16", D: "64" },
    correct: "A",
    explanation: "For an n×n matrix, det(kA) = kⁿ·det(A); here det(2A) = 2³·4 = 8·4 = 32.",
    source: "curated"
  },
  {
    id: "math-g12-trig-008",
    subject: "Mathematics",
    grade: 12,
    unit: "Trigonometry",
    difficulty: "impossible",
    type: "calculation",
    question: "If sin x + cos x = 1/2, what is the value of sin x · cos x?",
    options: { A: "−3/8", B: "3/8", C: "1/4", D: "−1/4" },
    correct: "A",
    explanation: "Square: (sin x + cos x)² = 1/4 → 1 + 2 sin x cos x = 1/4 → 2 sin x cos x = −3/4 → sin x cos x = −3/8.",
    source: "curated"
  },
  {
    id: "math-g12-prob-010",
    subject: "Mathematics",
    grade: 12,
    unit: "Probability & combinatorics",
    difficulty: "impossible",
    type: "calculation",
    question: "How many distinct arrangements are there of the letters in the word 'BANANA'?",
    options: { A: "60", B: "720", C: "120", D: "180" },
    correct: "A",
    explanation: "6 letters with A×3, N×2, B×1: 6!/(3!·2!·1!) = 720/12 = 60.",
    source: "curated"
  },
  {
    id: "math-g12-func-009",
    subject: "Mathematics",
    grade: 12,
    unit: "Functions & relations",
    difficulty: "impossible",
    type: "calculation",
    question: "If f(x) = x/(x − 1) for x ≠ 1, what is f(f(x)) (simplified)?",
    options: { A: "x", B: "x/(x − 1)", C: "1/x", D: "x − 1" },
    correct: "A",
    explanation: "f(f(x)) = f(x)/(f(x) − 1) = [x/(x−1)] / [x/(x−1) − 1] = [x/(x−1)] / [1/(x−1)] = x.",
    source: "curated"
  },
  {
    id: "math-g12-calc-014",
    subject: "Mathematics",
    grade: 12,
    unit: "Introduction to calculus",
    difficulty: "impossible",
    type: "calculation",
    question: "A box with a square base and open top must have volume 32. What base edge x minimizes its surface area?",
    options: { A: "4", B: "2", C: "8", D: "2√2" },
    correct: "A",
    explanation: "Height h = 32/x²; surface S = x² + 4xh = x² + 128/x. S′ = 2x − 128/x² = 0 → x³ = 64 → x = 4.",
    source: "curated"
  },
  {
    id: "math-g12-solid-005",
    subject: "Mathematics",
    grade: 12,
    unit: "Solid geometry",
    difficulty: "impossible",
    type: "calculation",
    question: "A sphere is inscribed in a cube of edge 6. What is the ratio of the sphere's volume to the cube's volume?",
    options: { A: "π/6", B: "π/3", C: "π/4", D: "π/2" },
    correct: "A",
    explanation: "Sphere radius = 3; V_sphere = (4/3)π(27) = 36π; V_cube = 216; ratio = 36π/216 = π/6.",
    source: "curated"
  },
  {
    id: "math-g12-stat-008",
    subject: "Mathematics",
    grade: 12,
    unit: "Statistics",
    difficulty: "impossible",
    type: "calculation",
    question: "A set of 5 numbers has mean 6 and population variance 4. If each number is multiplied by 3, what is the new variance?",
    options: { A: "36", B: "12", C: "4", D: "108" },
    correct: "A",
    explanation: "Multiplying every value by 3 multiplies variance by 3² = 9: new variance = 9·4 = 36.",
    source: "curated"
  },
  {
    id: "math-g12-vec-007",
    subject: "Mathematics",
    grade: 12,
    unit: "Vectors",
    difficulty: "impossible",
    type: "calculation",
    question: "For 3D vectors a = (1, 2, 2) and b = (2, 1, 2), what is the scalar projection of a onto b?",
    options: { A: "8/3", B: "8/9", C: "3/8", D: "4/3" },
    correct: "A",
    explanation: "Scalar projection = (a·b)/|b| = (2 + 2 + 4)/√(4+1+4) = 8/√9 = 8/3.",
    source: "curated"
  },
  {
    id: "math-g12-absineq-006",
    subject: "Mathematics",
    grade: 12,
    unit: "Absolute-value inequalities",
    difficulty: "impossible",
    type: "calculation",
    question: "Solve: |x − 1| + |x + 2| ≤ 5.",
    options: { A: "−3 ≤ x ≤ 2", B: "−2 ≤ x ≤ 1", C: "x ≤ 2", D: "−5 ≤ x ≤ 5" },
    correct: "A",
    explanation: "For x ≥ 1: (x−1)+(x+2) = 2x+1 ≤ 5 → x ≤ 2. For −2 ≤ x < 1: sum = 3 ≤ 5 (always). For x < −2: −(x−1)−(x+2) = −2x−1 ≤ 5 → x ≥ −3. Combined: −3 ≤ x ≤ 2.",
    source: "curated"
  },
  {
    id: "math-g12-rat-006",
    subject: "Mathematics",
    grade: 12,
    unit: "Rational expressions",
    difficulty: "impossible",
    type: "calculation",
    question: "If x + 1/x = 3, what is x³ + 1/x³?",
    options: { A: "18", B: "27", C: "21", D: "9" },
    correct: "A",
    explanation: "x³ + 1/x³ = (x + 1/x)³ − 3(x + 1/x) = 27 − 9 = 18.",
    source: "curated"
  },
  {
    id: "math-g12-seq-009",
    subject: "Mathematics",
    grade: 12,
    unit: "Sequences & series",
    difficulty: "impossible",
    type: "calculation",
    question: "The sum of the first n terms of a sequence is Sₙ = n² + 2n. What is the 5th term?",
    options: { A: "11", B: "35", C: "15", D: "10" },
    correct: "A",
    explanation: "aₙ = Sₙ − Sₙ₋₁ = (25 + 10) − (16 + 8) = 35 − 24 = 11.",
    source: "curated"
  },
  {
    id: "math-g12-trig-009",
    subject: "Mathematics",
    grade: 12,
    unit: "Trigonometry",
    difficulty: "impossible",
    type: "calculation",
    question: "What is the maximum value of f(x) = 3 sin x + 4 cos x?",
    options: { A: "5", B: "7", C: "4", D: "√7" },
    correct: "A",
    explanation: "a sin x + b cos x has maximum √(a² + b²) = √(9 + 16) = √25 = 5.",
    source: "curated"
  },
  {
    id: "math-g12-prob-011",
    subject: "Mathematics",
    grade: 12,
    unit: "Probability & combinatorics",
    difficulty: "impossible",
    type: "calculation",
    question: "Three fair coins are tossed. Given that at least one is a head, what is the probability all three are heads?",
    options: { A: "1/7", B: "1/8", C: "1/4", D: "3/8" },
    correct: "A",
    explanation: "P(all heads) = 1/8; P(at least one head) = 7/8; conditional = (1/8)/(7/8) = 1/7.",
    source: "curated"
  },
  {
    id: "math-g12-calc-015",
    subject: "Mathematics",
    grade: 12,
    unit: "Introduction to calculus",
    difficulty: "impossible",
    type: "calculation",
    question: "What is the area enclosed between y = x² and y = 2x?",
    options: { A: "4/3", B: "8/3", C: "2/3", D: "2" },
    correct: "A",
    explanation: "Curves meet at x = 0 and x = 2; area = ∫₀² (2x − x²) dx = [x² − x³/3]₀² = 4 − 8/3 = 4/3.",
    source: "curated"
  },
  {
    id: "math-g12-mat-007",
    subject: "Mathematics",
    grade: 12,
    unit: "Matrices & determinants",
    difficulty: "impossible",
    type: "calculation",
    question: "For what value of k is the matrix [[k, 2], [3, k]] singular (non-invertible)?",
    options: { A: "k = ±√6", B: "k = 6", C: "k = ±6", D: "k = 0" },
    correct: "A",
    explanation: "Singular means det = 0: k² − 6 = 0 → k = ±√6.",
    source: "curated"
  },
  {
    id: "math-g12-linprog-004",
    subject: "Mathematics",
    grade: 12,
    unit: "Linear programming",
    difficulty: "impossible",
    type: "calculation",
    question: "Minimize C = 2x + 3y subject to x + y ≥ 6, x + 2y ≥ 8, x ≥ 0, y ≥ 0. What is the minimum?",
    options: { A: "14", B: "12", C: "16", D: "13" },
    correct: "A",
    explanation: "Corner points of the feasible region: (8,0)→16, (0,6)→18, and intersection of x+y=6 & x+2y=8 is (4,2)→2(4)+3(2)=14. Minimum is 14.",
    source: "curated"
  },
  {
    id: "math-g12-func-010",
    subject: "Mathematics",
    grade: 12,
    unit: "Functions & relations",
    difficulty: "impossible",
    type: "calculation",
    question: "If f(x + 1) = f(x) + 2x + 1 for all x and f(0) = 3, what is f(4)?",
    options: { A: "19", B: "16", C: "15", D: "11" },
    correct: "A",
    explanation: "f(x+1) − f(x) = 2x + 1 implies f(x) = x² + 3; f(4) = 16 + 3 = 19.",
    source: "curated"
  }
];
